import { Router } from 'express';
import type { Request, Response } from 'express';
import { db } from '../db.js';
import {
  extractionReviewQueue,
  dashboardTemplates,
} from '../db/schema.js';
import { eq, and } from 'drizzle-orm';

export function registerApprovalCenterRoutes(app: Router) {
  const router = Router();

  /**
   * GET /api/approval-center/extraction-items
   * Get all extraction review items pending approval
   */
  router.get('/extraction-items', async (req: Request, res: Response) => {
    try {
      const items = await db
        .select()
        .from(extractionReviewQueue)
        .where(eq(extractionReviewQueue.reviewStatus, 'pending'))
        .orderBy(extractionReviewQueue.createdAt);

      // Add source agent based on item type
      const itemsWithSource = items.map(item => ({
        ...item,
        sourceAgent: 'policy-as-code-extractor' // All extraction items come from this agent
      }));

      res.json({
        items: itemsWithSource,
        count: items.length
      });
    } catch (error: any) {
      console.error('Fetch extraction items error:', error);
      res.status(500).json({ error: error.message || 'Failed to fetch extraction items' });
    }
  });

  /**
   * GET /api/approval-center/dashboard-items
   * Get all auto-generated dashboards pending approval
   */
  router.get('/dashboard-items', async (req: Request, res: Response) => {
    try {
      const items = await db
        .select()
        .from(dashboardTemplates)
        .where(
          and(
            eq(dashboardTemplates.autoGenerated, true),
            eq(dashboardTemplates.isActive, false) // Pending approval
          )
        )
        .orderBy(dashboardTemplates.createdAt);

      res.json({
        items,
        count: items.length
      });
    } catch (error: any) {
      console.error('Fetch dashboard items error:', error);
      res.status(500).json({ error: error.message || 'Failed to fetch dashboard items' });
    }
  });

  /**
   * POST /api/approval-center/dashboards/:id/approve
   * Approve and activate a dashboard
   */
  router.post('/dashboards/:id/approve', async (req: Request, res: Response) => {
    try {
      const { id } = req.params;

      await db
        .update(dashboardTemplates)
        .set({
          isActive: true,
          updatedAt: new Date()
        })
        .where(eq(dashboardTemplates.id, id));

      res.json({ success: true, message: 'Dashboard approved and activated' });
    } catch (error: any) {
      console.error('Dashboard approval error:', error);
      res.status(500).json({ error: error.message || 'Failed to approve dashboard' });
    }
  });

  /**
   * DELETE /api/approval-center/dashboards/:id/reject
   * Reject and delete a dashboard
   */
  router.delete('/dashboards/:id/reject', async (req: Request, res: Response) => {
    try {
      const { id } = req.params;

      await db
        .delete(dashboardTemplates)
        .where(eq(dashboardTemplates.id, id));

      res.json({ success: true, message: 'Dashboard rejected and deleted' });
    } catch (error: any) {
      console.error('Dashboard rejection error:', error);
      res.status(500).json({ error: error.message || 'Failed to reject dashboard' });
    }
  });

  /**
   * GET /api/approval-center/stats
   * Get approval center statistics
   */
  router.get('/stats', async (req: Request, res: Response) => {
    try {
      const extractionItems = await db
        .select()
        .from(extractionReviewQueue);

      const dashboards = await db
        .select()
        .from(dashboardTemplates)
        .where(eq(dashboardTemplates.autoGenerated, true));

      const stats = {
        total: extractionItems.length + dashboards.length,
        pending: extractionItems.filter(i => i.reviewStatus === 'pending').length +
                 dashboards.filter(d => !d.isActive).length,
        approved: extractionItems.filter(i => i.reviewStatus === 'approved').length +
                  dashboards.filter(d => d.isActive).length,
        rejected: extractionItems.filter(i => i.reviewStatus === 'rejected').length,
        bySource: {
          'policy-as-code-extractor': extractionItems.length,
          'dashboard-generator': dashboards.length
        },
        byType: extractionItems.reduce((acc, item) => {
          acc[item.itemType] = (acc[item.itemType] || 0) + 1;
          return acc;
        }, {} as Record<string, number>)
      };

      res.json(stats);
    } catch (error: any) {
      console.error('Stats error:', error);
      res.status(500).json({ error: error.message || 'Failed to fetch stats' });
    }
  });

  app.use('/api/approval-center', router);
}
