/**
 * CLARITY CHAT — universal portfolio assistant
 *
 * Anthropic-powered chat with tool-use grounded in the Palantir knowledge graph.
 * The model can call tools to look up real project data, dependencies, risks,
 * insights, etc. — every answer is anchored in live ontology data.
 */

import { Router, Request, Response } from 'express';
import Anthropic from '@anthropic-ai/sdk';
import { palantirGraphService } from '../services/PalantirGraphService.js';

const router = Router();

// ─── Simple in-memory rate limit (per-IP) — bounds Anthropic spend ──────────
// Each request can fan out to ~6 LLM calls, so we keep this tight.
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_PER_WINDOW = 15;
const rateBuckets = new Map<string, { count: number; resetAt: number }>();
function checkRate(ip: string): boolean {
  const now = Date.now();
  const b = rateBuckets.get(ip);
  if (!b || now > b.resetAt) {
    rateBuckets.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return true;
  }
  if (b.count >= RATE_LIMIT_MAX_PER_WINDOW) return false;
  b.count++;
  return true;
}

// Clip conversation history to bound context size and cost.
const MAX_HISTORY_MESSAGES = 16;

const FRIENDLY_TO_ATLAS: Record<string, string> = {
  project: 'AtlasProject', risk: 'AtlasRisk', objective: 'AtlasObjective',
  keyresult: 'AtlasKeyResult', dependency: 'AtlasDependency', team: 'AtlasTeam',
  person: 'AtlasPerson', budget: 'AtlasBudget', kpi: 'AtlasKpi',
  insight: 'AtlasInsight', checkpoint: 'AtlasGovernanceCheckpoint',
  transformation: 'AtlasTransformation', epic: 'AtlasEpic', feature: 'AtlasFeature',
};
const resolve = (t: string) => FRIENDLY_TO_ATLAS[t.toLowerCase()] || t;

// ─── Tools the model can call ────────────────────────────────────────────────
const TOOLS: Anthropic.Tool[] = [
  {
    name: 'search_nodes',
    description: 'Full-text search the portfolio knowledge graph. Returns matching projects, risks, dependencies, KPIs, etc. Use to find an entity by name or keyword.',
    input_schema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search keyword or phrase' },
        type: { type: 'string', enum: Object.keys(FRIENDLY_TO_ATLAS), description: 'Entity type to search' },
        limit: { type: 'number', description: 'Max results (default 10)' },
      },
      required: ['query', 'type'],
    },
  },
  {
    name: 'get_node',
    description: 'Fetch full properties of a specific node by id and type.',
    input_schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        type: { type: 'string', enum: Object.keys(FRIENDLY_TO_ATLAS) },
      },
      required: ['id', 'type'],
    },
  },
  {
    name: 'get_neighbors',
    description: 'Get all directly-connected nodes (risks, dependencies, KPIs, budgets, teams, etc.) for a given node. Use this to understand what surrounds a project or to traverse cross-project links.',
    input_schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        type: { type: 'string', enum: Object.keys(FRIENDLY_TO_ATLAS) },
      },
      required: ['id', 'type'],
    },
  },
  {
    name: 'list_dependencies',
    description: 'List portfolio dependencies. Optionally filter by source project, target project, or status (e.g. "blocked"). Use this for cross-project dependency questions.',
    input_schema: {
      type: 'object',
      properties: {
        sourceProjectId: { type: 'string' },
        targetProjectId: { type: 'string' },
        status: { type: 'string', description: 'e.g. blocked, in_progress, resolved' },
        limit: { type: 'number' },
      },
    },
  },
  {
    name: 'get_cross_domain_insights',
    description: 'Get the latest portfolio-wide insights generated by the rules engine: orphaned projects, unmitigated risks, blocked cross-project dependencies, dependency hotspots, etc.',
    input_schema: { type: 'object', properties: {} },
  },
  {
    name: 'get_node_insights',
    description: 'Get insights and relationships for one specific node (e.g. a project) — health, blocked dependencies, unmitigated risks attached to it.',
    input_schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        type: { type: 'string', enum: Object.keys(FRIENDLY_TO_ATLAS) },
      },
      required: ['id', 'type'],
    },
  },
  {
    name: 'list_projects',
    description: 'List all projects in the portfolio with high-level health metrics (status, cpi, spi). Use for portfolio-level overview questions.',
    input_schema: {
      type: 'object',
      properties: { limit: { type: 'number', description: 'Max projects (default 50)' } },
    },
  },
];

// ─── Tool implementations ────────────────────────────────────────────────────
async function execTool(name: string, input: any): Promise<any> {
  await palantirGraphService.initialize();
  const svc = (palantirGraphService as any).palantirService;
  if (!svc) return { error: 'Palantir service unavailable' };

  switch (name) {
    case 'search_nodes': {
      const atlas = resolve(input.type);
      const r = await svc.searchObjects(atlas, { type: 'contains', field: '__title', value: input.query }, { pageSize: input.limit || 10 });
      const SUB = ['[task]', '[story]', '[feature]', '[subtask]'];
      const filtered = (r.data || []).filter((n: any) => {
        const label = (n.title || n.name || n.__title || '').toLowerCase();
        return !SUB.some(p => label.startsWith(p));
      });
      return { count: filtered.length, results: filtered.slice(0, input.limit || 10).map((n: any) => ({
        id: n.id || n.__primaryKey, type: atlas,
        label: n.title || n.name || n.__title,
        status: n.status, severity: n.severity,
      })) };
    }
    case 'get_node': {
      const atlas = resolve(input.type);
      const obj = await svc.getObject(atlas, input.id);
      return obj ? { type: atlas, properties: obj } : { error: 'Not found' };
    }
    case 'get_neighbors': {
      const atlas = resolve(input.type);
      const neighbors = await palantirGraphService.getNodeNeighbors(atlas, input.id);
      return { count: neighbors.length, neighbors: neighbors.map(n => ({
        id: n.id, type: n.type, label: n.label, status: n.status, severity: n.severity,
      })) };
    }
    case 'list_dependencies': {
      let r;
      if (input.sourceProjectId) {
        r = await svc.searchObjects('AtlasDependency', { type: 'eq', field: 'sourceProjectId', value: input.sourceProjectId }, { pageSize: input.limit || 50 });
      } else if (input.targetProjectId) {
        r = await svc.searchObjects('AtlasDependency', { type: 'eq', field: 'targetProjectId', value: input.targetProjectId }, { pageSize: input.limit || 50 });
      } else {
        r = await svc.listObjects('AtlasDependency', { pageSize: input.limit || 50 });
      }
      let deps = r.data || [];
      if (input.status) deps = deps.filter((d: any) => d.status === input.status);
      return { count: deps.length, dependencies: deps.map((d: any) => ({
        id: d.id || d.dependencyId,
        title: d.title || d.description,
        sourceProjectId: d.sourceProjectId,
        targetProjectId: d.targetProjectId,
        status: d.status,
        severity: d.severity,
        dueDate: d.dueDate,
      })) };
    }
    case 'get_cross_domain_insights': {
      const insights = await palantirGraphService.generateCrossDomainInsights();
      return { count: insights.length, insights };
    }
    case 'get_node_insights': {
      const atlas = resolve(input.type);
      const result = await palantirGraphService.getNodeInsights(atlas, input.id);
      return result;
    }
    case 'list_projects': {
      const r = await svc.listObjects('AtlasProject', { pageSize: (input.limit || 50) * 3 });
      const SUB = ['[task]', '[story]', '[feature]', '[subtask]', '[agent]', '[jira'];
      const real = (r.data || []).filter((p: any) => {
        const label = (p.name || p.title || '').toLowerCase();
        return !SUB.some(prefix => label.startsWith(prefix));
      }).slice(0, input.limit || 50);
      return { count: real.length, projects: real.map((p: any) => ({
        id: p.id || p.projectId,
        name: p.name || p.title,
        status: p.status,
        cpi: p.cpi, spi: p.spi,
        budget: p.budget, actualCost: p.actualCost,
        progress: p.milestoneProgress,
      })) };
    }
    default:
      return { error: `Unknown tool: ${name}` };
  }
}

// ─── /api/clarity-chat ───────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are Clarity, the AI assistant for Kyndryl's enterprise portfolio platform. You help executives and PMOs interrogate live data about projects, cross-project dependencies, risks, KPIs, budgets, and strategic objectives.

Rules:
- ALWAYS ground answers in real data by calling tools. Never invent project names, IDs, or numbers.
- For cross-project dependency questions, prefer list_dependencies (with sourceProjectId/targetProjectId/status) and get_neighbors.
- For "what's wrong with the portfolio" questions, call get_cross_domain_insights first.
- For specific project deep-dives, call search_nodes → get_node → get_node_insights → get_neighbors.
- Be concise. Use bullet points when listing multiple items. Quote IDs in backticks like \`PRJ-001\`.
- If a tool returns no data, say so plainly. Do not fabricate.`;

router.post('/', async (req: Request, res: Response) => {
  try {
    const ip = (req.ip || req.socket.remoteAddress || 'unknown').toString();
    if (!checkRate(ip)) {
      return res.status(429).json({ error: `Rate limit exceeded (${RATE_LIMIT_MAX_PER_WINDOW} req/min). Please slow down.` });
    }

    const { messages } = req.body as { messages: Array<{ role: 'user' | 'assistant'; content: string }> };
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: 'messages array required' });
    }
    if (!process.env.ANTHROPIC_API_KEY) {
      return res.status(503).json({ error: 'ANTHROPIC_API_KEY not configured' });
    }

    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    // Keep only the last MAX_HISTORY_MESSAGES turns to bound context size and cost.
    const trimmed = messages.slice(-MAX_HISTORY_MESSAGES);
    const conversation: Anthropic.MessageParam[] = trimmed.map(m => ({
      role: m.role,
      content: m.content,
    }));

    const toolCalls: Array<{ name: string; input: any; result: any }> = [];
    let finalText = '';

    // Tool-use loop (max 6 hops to bound latency/cost)
    for (let hop = 0; hop < 6; hop++) {
      const resp = await client.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1500,
        system: SYSTEM_PROMPT,
        tools: TOOLS,
        messages: conversation,
      });

      const toolUses = resp.content.filter(b => b.type === 'tool_use') as Anthropic.ToolUseBlock[];
      const textBlocks = resp.content.filter(b => b.type === 'text') as Anthropic.TextBlock[];

      if (toolUses.length === 0) {
        finalText = textBlocks.map(t => t.text).join('\n').trim();
        break;
      }

      // Execute tools and feed results back
      conversation.push({ role: 'assistant', content: resp.content });
      const toolResults: Anthropic.ToolResultBlockParam[] = [];
      for (const tu of toolUses) {
        let result: any;
        let isError = false;
        try {
          result = await execTool(tu.name, tu.input);
        } catch (e: any) {
          result = { error: e.message || 'Tool execution failed' };
          isError = true;
        }
        toolCalls.push({ name: tu.name, input: tu.input, result });
        toolResults.push({
          type: 'tool_result',
          tool_use_id: tu.id,
          content: JSON.stringify(result).slice(0, 8000),
          is_error: isError,
        });
      }
      conversation.push({ role: 'user', content: toolResults });

      if (resp.stop_reason === 'end_turn') {
        finalText = textBlocks.map(t => t.text).join('\n').trim();
        break;
      }
    }

    if (!finalText) finalText = 'I gathered some data but could not produce a final answer. Please rephrase your question.';

    res.json({ reply: finalText, toolCalls });
  } catch (e: any) {
    console.error('[ClarityChat]', e);
    res.status(500).json({ error: e.message || 'Chat failed' });
  }
});

export default router;
