/**
 * UNIFIED APPROVAL CENTER
 *
 * Single pane of glass for all Human-in-the-Loop (HITL) approvals:
 * - AI-extracted data (metrics, OKRs, org units, rules)
 * - Auto-generated dashboards
 * - Agent-proposed changes
 * - Workflow modifications
 *
 * Filterable by: source agent, item type, confidence score, date
 */

import { AdminLayout } from '@/components/AdminLayout';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  CheckCircle2,
  X,
  Edit,
  Sparkles,
  AlertCircle,
  Filter,
  Search,
  Eye,
  LayoutDashboard,
  TrendingUp,
  Target,
  Shield,
  Building2,
  Clock,
  User,
  Bot,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import { format } from 'date-fns';

interface ExtractionReviewItem {
  id: string;
  itemType: 'organizational_unit' | 'metric' | 'objective' | 'rule' | 'risk';
  itemData: any;
  confidenceScore: number;
  requiresHumanReview: boolean;
  sourceAgent: string;
  sourceTextExcerpt: string;
  sourcePageNumber?: number;
  reviewStatus: 'pending' | 'approved' | 'rejected' | 'modified';
  createdAt: string;
}

interface DashboardReviewItem {
  id: string;
  templateName: string;
  templateType: string;
  description: string;
  layoutConfig: any;
  autoGenerated: boolean;
  generationMetadata: any;
  createdAt: string;
}

interface ApprovalStats {
  total: number;
  pending: number;
  approved: number;
  rejected: number;
  bySource: Record<string, number>;
  byType: Record<string, number>;
}

export default function ApprovalCenter() {
  const [activeTab, setActiveTab] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [sourceFilter, setSourceFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [confidenceFilter, setConfidenceFilter] = useState('all');
  const [previewItem, setPreviewItem] = useState<any>(null);
  const [showPreviewDialog, setShowPreviewDialog] = useState(false);
  const queryClient = useQueryClient();

  // Fetch extraction review items
  const { data: extractionItems, isLoading: loadingExtraction } = useQuery<ExtractionReviewItem[]>({
    queryKey: ['approval-extraction-items'],
    queryFn: async () => {
      const res = await fetch('/api/approval-center/extraction-items');
      if (!res.ok) throw new Error('Failed to fetch extraction items');
      const data = await res.json();
      return data.items || [];
    },
  });

  // Fetch pending dashboards
  const { data: dashboardItems, isLoading: loadingDashboards } = useQuery<DashboardReviewItem[]>({
    queryKey: ['approval-dashboard-items'],
    queryFn: async () => {
      const res = await fetch('/api/approval-center/dashboard-items');
      if (!res.ok) throw new Error('Failed to fetch dashboard items');
      const data = await res.json();
      return data.items || [];
    },
  });

  // Approve extraction item mutation
  const approveExtractionMutation = useMutation({
    mutationFn: async (itemId: string) => {
      const res = await fetch(`/api/company-profile/review-queue/${itemId}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!res.ok) throw new Error('Failed to approve item');
      return res.json();
    },
    onSuccess: () => {
      toast.success('Item approved');
      queryClient.invalidateQueries({ queryKey: ['approval-extraction-items'] });
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to approve item');
    },
  });

  // Reject extraction item mutation
  const rejectExtractionMutation = useMutation({
    mutationFn: async ({ itemId, reason }: { itemId: string; reason?: string }) => {
      const res = await fetch(`/api/company-profile/review-queue/${itemId}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason }),
      });
      if (!res.ok) throw new Error('Failed to reject item');
      return res.json();
    },
    onSuccess: () => {
      toast.success('Item rejected');
      queryClient.invalidateQueries({ queryKey: ['approval-extraction-items'] });
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to reject item');
    },
  });

  // Approve dashboard mutation
  const approveDashboardMutation = useMutation({
    mutationFn: async (dashboardId: string) => {
      const res = await fetch(`/api/approval-center/dashboards/${dashboardId}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!res.ok) throw new Error('Failed to approve dashboard');
      return res.json();
    },
    onSuccess: () => {
      toast.success('Dashboard approved and activated');
      queryClient.invalidateQueries({ queryKey: ['approval-dashboard-items'] });
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to approve dashboard');
    },
  });

  // Reject dashboard mutation
  const rejectDashboardMutation = useMutation({
    mutationFn: async (dashboardId: string) => {
      const res = await fetch(`/api/approval-center/dashboards/${dashboardId}/reject`, {
        method: 'DELETE',
      });
      if (!res.ok) throw new Error('Failed to reject dashboard');
      return res.json();
    },
    onSuccess: () => {
      toast.success('Dashboard rejected and deleted');
      queryClient.invalidateQueries({ queryKey: ['approval-dashboard-items'] });
    },
    onError: (error: any) => {
      toast.error(error.message || 'Failed to reject dashboard');
    },
  });

  // Bulk approve high confidence items
  const bulkApproveHighConfidence = async () => {
    const highConfidenceItems = extractionItems?.filter(item => item.confidenceScore >= 0.85) || [];

    for (const item of highConfidenceItems) {
      await approveExtractionMutation.mutateAsync(item.id);
    }

    toast.success(`Approved ${highConfidenceItems.length} high-confidence items`);
  };

  const getItemIcon = (type: string) => {
    switch (type) {
      case 'organizational_unit':
        return Building2;
      case 'metric':
      case 'kpi':
        return TrendingUp;
      case 'objective':
        return Target;
      case 'rule':
        return Shield;
      case 'dashboard':
        return LayoutDashboard;
      default:
        return AlertCircle;
    }
  };

  const getSourceBadgeColor = (source: string) => {
    const colors: Record<string, string> = {
      'policy-as-code-extractor': 'bg-purple-100 text-purple-700 dark:bg-purple-900/30',
      'dashboard-generator': 'bg-blue-100 text-blue-700 dark:bg-blue-900/30',
      'ontology-mapper': 'bg-green-100 text-green-700 dark:bg-green-900/30',
      'risk-analyzer': 'bg-red-100 text-red-700 dark:bg-red-900/30',
    };
    return colors[source] || 'bg-gray-100 text-gray-700 dark:bg-gray-900/30';
  };

  // Filter items
  const filteredExtractionItems = extractionItems?.filter((item) => {
    const matchesSearch =
      searchQuery === '' ||
      JSON.stringify(item.itemData).toLowerCase().includes(searchQuery.toLowerCase());

    const matchesSource =
      sourceFilter === 'all' || item.sourceAgent === sourceFilter;

    const matchesType = typeFilter === 'all' || item.itemType === typeFilter;

    const matchesConfidence =
      confidenceFilter === 'all' ||
      (confidenceFilter === 'high' && item.confidenceScore >= 0.85) ||
      (confidenceFilter === 'medium' && item.confidenceScore >= 0.7 && item.confidenceScore < 0.85) ||
      (confidenceFilter === 'low' && item.confidenceScore < 0.7);

    const matchesStatus =
      activeTab === 'all' ||
      (activeTab === 'pending' && item.reviewStatus === 'pending') ||
      (activeTab === 'approved' && item.reviewStatus === 'approved') ||
      (activeTab === 'rejected' && item.reviewStatus === 'rejected');

    return matchesSearch && matchesSource && matchesType && matchesConfidence && matchesStatus;
  }) || [];

  const filteredDashboardItems = dashboardItems || [];

  // Calculate stats
  const stats: ApprovalStats = {
    total: (extractionItems?.length || 0) + (dashboardItems?.length || 0),
    pending: (extractionItems?.filter(i => i.reviewStatus === 'pending').length || 0) + (dashboardItems?.length || 0),
    approved: extractionItems?.filter(i => i.reviewStatus === 'approved').length || 0,
    rejected: extractionItems?.filter(i => i.reviewStatus === 'rejected').length || 0,
    bySource: {},
    byType: {},
  };

  const isLoading = loadingExtraction || loadingDashboards;

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <CheckCircle2 className="w-8 h-8 text-blue-600" />
              <h1 className="text-3xl font-bold">Approval Center</h1>
            </div>
            <p className="text-muted-foreground">
              Review and approve AI-generated content before it becomes active
            </p>
          </div>

          <Button onClick={bulkApproveHighConfidence} className="gap-2" variant="outline">
            <Sparkles className="w-4 h-4" />
            Approve All High Confidence (≥85%)
          </Button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 dark:bg-blue-900/20 rounded-lg">
                  <Clock className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Pending Review</p>
                  <p className="text-2xl font-bold">{stats.pending}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-green-100 dark:bg-green-900/20 rounded-lg">
                  <CheckCircle2 className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Approved</p>
                  <p className="text-2xl font-bold">{stats.approved}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-red-100 dark:bg-red-900/20 rounded-lg">
                  <X className="w-5 h-5 text-red-600" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Rejected</p>
                  <p className="text-2xl font-bold">{stats.rejected}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-purple-100 dark:bg-purple-900/20 rounded-lg">
                  <Bot className="w-5 h-5 text-purple-600" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Total Items</p>
                  <p className="text-2xl font-bold">{stats.total}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Filter className="w-5 h-5" />
              <CardTitle>Filters</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Search items..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>

              <Select value={sourceFilter} onValueChange={setSourceFilter}>
                <SelectTrigger>
                  <SelectValue placeholder="Source Agent" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Sources</SelectItem>
                  <SelectItem value="policy-as-code-extractor">Policy-as-Code Extractor</SelectItem>
                  <SelectItem value="dashboard-generator">Dashboard Generator</SelectItem>
                  <SelectItem value="ontology-mapper">Ontology Mapper</SelectItem>
                  <SelectItem value="risk-analyzer">Risk Analyzer</SelectItem>
                </SelectContent>
              </Select>

              <Select value={typeFilter} onValueChange={setTypeFilter}>
                <SelectTrigger>
                  <SelectValue placeholder="Item Type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  <SelectItem value="organizational_unit">Org Units</SelectItem>
                  <SelectItem value="metric">Metrics</SelectItem>
                  <SelectItem value="objective">Objectives</SelectItem>
                  <SelectItem value="rule">Rules</SelectItem>
                  <SelectItem value="dashboard">Dashboards</SelectItem>
                </SelectContent>
              </Select>

              <Select value={confidenceFilter} onValueChange={setConfidenceFilter}>
                <SelectTrigger>
                  <SelectValue placeholder="Confidence" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Confidence</SelectItem>
                  <SelectItem value="high">High (≥85%)</SelectItem>
                  <SelectItem value="medium">Medium (70-84%)</SelectItem>
                  <SelectItem value="low">Low (&lt;70%)</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList>
            <TabsTrigger value="all">All ({stats.total})</TabsTrigger>
            <TabsTrigger value="pending">Pending ({stats.pending})</TabsTrigger>
            <TabsTrigger value="approved">Approved ({stats.approved})</TabsTrigger>
            <TabsTrigger value="rejected">Rejected ({stats.rejected})</TabsTrigger>
          </TabsList>

          <TabsContent value={activeTab} className="space-y-6 mt-6">
            {/* Extracted Data Items */}
            {filteredExtractionItems.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-lg font-semibold">Extracted Data</h3>
                {filteredExtractionItems.map((item) => {
                  const Icon = getItemIcon(item.itemType);

                  return (
                    <Card key={item.id}>
                      <CardContent className="py-4">
                        <div className="flex items-start justify-between">
                          <div className="flex items-start gap-3 flex-1">
                            <Icon className="w-5 h-5 text-muted-foreground mt-1" />
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-2">
                                <span className="font-semibold">
                                  {item.itemData.metric_name ||
                                   item.itemData.objective_name ||
                                   item.itemData.unit_name ||
                                   item.itemData.rule_name ||
                                   item.itemData.name ||
                                   'Unnamed Item'}
                                </span>
                                <Badge variant="outline" className="capitalize">
                                  {item.itemType.replace('_', ' ')}
                                </Badge>
                                <Badge
                                  variant={item.confidenceScore >= 0.85 ? 'default' : 'secondary'}
                                >
                                  {Math.round(item.confidenceScore * 100)}% confidence
                                </Badge>
                                <Badge variant="outline" className={getSourceBadgeColor(item.sourceAgent)}>
                                  <Bot className="w-3 h-3 mr-1" />
                                  {item.sourceAgent}
                                </Badge>
                              </div>
                              {item.itemData.description && (
                                <p className="text-sm text-muted-foreground mb-2">
                                  {item.itemData.description}
                                </p>
                              )}
                              <div className="text-xs text-muted-foreground bg-muted/30 rounded p-2">
                                <span className="font-medium">Source:</span> {item.sourceTextExcerpt}
                                {item.sourcePageNumber && ` (Page ${item.sourcePageNumber})`}
                              </div>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 ml-4">
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => {
                                setPreviewItem(item);
                                setShowPreviewDialog(true);
                              }}
                            >
                              <Eye className="w-4 h-4" />
                            </Button>
                            <Button
                              size="sm"
                              variant="default"
                              onClick={() => approveExtractionMutation.mutate(item.id)}
                              disabled={approveExtractionMutation.isPending}
                            >
                              <CheckCircle2 className="w-4 h-4" />
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => rejectExtractionMutation.mutate({ itemId: item.id })}
                              disabled={rejectExtractionMutation.isPending}
                            >
                              <X className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            )}

            {/* Dashboard Items */}
            {filteredDashboardItems.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-lg font-semibold">Auto-Generated Dashboards</h3>
                {filteredDashboardItems.map((dashboard) => (
                  <Card key={dashboard.id}>
                    <CardContent className="py-4">
                      <div className="flex items-start justify-between">
                        <div className="flex items-start gap-3 flex-1">
                          <LayoutDashboard className="w-5 h-5 text-blue-600 mt-1" />
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <span className="font-semibold">{dashboard.templateName}</span>
                              <Badge variant="outline" className="capitalize">
                                {dashboard.templateType}
                              </Badge>
                              <Badge variant="secondary" className="gap-1">
                                <Sparkles className="w-3 h-3" />
                                Auto-Generated
                              </Badge>
                              <Badge variant="outline" className={getSourceBadgeColor('dashboard-generator')}>
                                <Bot className="w-3 h-3 mr-1" />
                                dashboard-generator
                              </Badge>
                            </div>
                            <p className="text-sm text-muted-foreground mb-2">{dashboard.description}</p>
                            <div className="text-xs text-muted-foreground">
                              Generated: {format(new Date(dashboard.createdAt), 'MMM d, yyyy h:mm a')}
                              {' • '}
                              {dashboard.layoutConfig.widgets?.length || 0} widgets
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-2 ml-4">
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => {
                              setPreviewItem(dashboard);
                              setShowPreviewDialog(true);
                            }}
                          >
                            <Eye className="w-4 h-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="default"
                            onClick={() => approveDashboardMutation.mutate(dashboard.id)}
                            disabled={approveDashboardMutation.isPending}
                          >
                            <CheckCircle2 className="w-4 h-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => rejectDashboardMutation.mutate(dashboard.id)}
                            disabled={rejectDashboardMutation.isPending}
                          >
                            <X className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}

            {/* Empty State */}
            {filteredExtractionItems.length === 0 && filteredDashboardItems.length === 0 && !isLoading && (
              <Card>
                <CardContent className="py-12 text-center">
                  <CheckCircle2 className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                  <h3 className="text-lg font-semibold mb-2">All Caught Up!</h3>
                  <p className="text-muted-foreground">
                    {activeTab === 'pending'
                      ? 'No items pending review'
                      : activeTab === 'approved'
                      ? 'No approved items'
                      : activeTab === 'rejected'
                      ? 'No rejected items'
                      : 'No items to review'}
                  </p>
                </CardContent>
              </Card>
            )}
          </TabsContent>
        </Tabs>
      </div>

      {/* Preview Dialog */}
      <Dialog open={showPreviewDialog} onOpenChange={setShowPreviewDialog}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Item Preview</DialogTitle>
            <DialogDescription>
              Review the details of this AI-generated item
            </DialogDescription>
          </DialogHeader>
          {previewItem && (
            <div className="py-4">
              <pre className="bg-muted p-4 rounded-lg overflow-auto text-sm">
                {JSON.stringify(previewItem, null, 2)}
              </pre>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowPreviewDialog(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AdminLayout>
  );
}
