/**
 * VOICE BRIEFINGS ADMIN PAGE
 *
 * Manage NotebookLM-style podcast briefings:
 * - Generate new briefings (project, portfolio, weekly summary)
 * - View briefing history
 * - Configure voice settings and preferences
 * - Manage API keys (OpenAI TTS)
 */

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AdminLayout } from '@/components/AdminLayout';
import { VoiceBriefingPlayer } from '@/components/VoiceBriefingPlayer';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Mic,
  Settings,
  Clock,
  PlayCircle,
  Download,
  Trash2,
  RefreshCw,
  Users,
  Key,
  CheckCircle,
  XCircle,
  AlertCircle,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';

interface BriefingSettings {
  openaiApiKey: string;
  defaultVoice: 'alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer';
  speakingSpeed: number;
  autoGenerateDaily: boolean;
  notifyOnComplete: boolean;
}

interface Briefing {
  id: string;
  type: 'project' | 'portfolio' | 'weekly_summary' | 'morning_briefing';
  projectId?: string;
  projectName?: string;
  audioUrl: string;
  duration: number;
  createdAt: string;
}

export default function VoiceBriefings() {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('generate');
  const [selectedProjectId, setSelectedProjectId] = useState('');
  const [briefingType, setBriefingType] = useState<'project' | 'portfolio' | 'weekly_summary' | 'morning_briefing'>('morning_briefing');
  const [selectedAgents, setSelectedAgents] = useState<string[]>(['VRO', 'PMO']);

  // Settings state
  const [settings, setSettings] = useState<BriefingSettings>({
    openaiApiKey: '',
    defaultVoice: 'nova',
    speakingSpeed: 1.0,
    autoGenerateDaily: false,
    notifyOnComplete: true,
  });

  // Check API configuration
  const { data: apiStatus } = useQuery({
    queryKey: ['voice-briefing-status'],
    queryFn: async () => {
      try {
        const response = await fetch('/api/voice-briefings/status');
        if (!response.ok) {
          return { configured: false, error: 'Unable to check status' };
        }
        return response.json();
      } catch (error) {
        return { configured: false, error: 'Connection failed' };
      }
    },
  });

  // Fetch briefings history
  const { data: briefingsData, refetch: refetchBriefings } = useQuery({
    queryKey: ['voice-briefings-history'],
    queryFn: async () => {
      const response = await fetch('/api/voice-briefings');
      if (!response.ok) throw new Error('Failed to fetch briefings');
      return response.json();
    },
  });

  // Fetch projects for selection
  const { data: projectsData } = useQuery({
    queryKey: ['projects-list'],
    queryFn: async () => {
      const response = await fetch('/api/projects');
      if (!response.ok) throw new Error('Failed to fetch projects');
      return response.json();
    },
  });

  const handleSaveSettings = async () => {
    try {
      const response = await fetch('/api/admin/settings/voice-briefings', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings),
      });

      if (!response.ok) throw new Error('Failed to save settings');

      toast({
        title: 'Settings Saved',
        description: 'Voice briefing settings have been updated.',
      });
    } catch (error: any) {
      toast({
        title: 'Save Failed',
        description: error.message,
        variant: 'destructive',
      });
    }
  };

  const handleDeleteBriefing = async (briefingId: string) => {
    try {
      const response = await fetch(`/api/voice-briefings/${briefingId}`, {
        method: 'DELETE',
      });

      if (!response.ok) throw new Error('Failed to delete briefing');

      toast({
        title: 'Briefing Deleted',
        description: 'The briefing has been removed.',
      });

      refetchBriefings();
    } catch (error: any) {
      toast({
        title: 'Delete Failed',
        description: error.message,
        variant: 'destructive',
      });
    }
  };

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            <Mic className="w-8 h-8 text-primary" />
            Voice Briefings
          </h1>
          <p className="text-muted-foreground mt-2">
            Generate and manage NotebookLM-style podcast briefings with AI hosts
          </p>
        </div>

        {/* API Status Banner */}
        {apiStatus && (
          <Card className={apiStatus.configured ? 'border-green-200 bg-green-50' : 'border-yellow-200 bg-yellow-50'}>
            <CardContent className="pt-6">
              <div className="flex items-start gap-4">
                {apiStatus.configured ? (
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0" />
                ) : (
                  <AlertCircle className="w-6 h-6 text-yellow-600 flex-shrink-0" />
                )}
                <div className="flex-1">
                  <h4 className="font-semibold text-sm mb-1">
                    {apiStatus.configured
                      ? 'Voice Briefings Ready'
                      : 'Configuration Required'}
                  </h4>
                  <p className="text-sm text-muted-foreground">
                    {apiStatus.configured
                      ? 'OpenAI TTS is configured and ready to generate podcast briefings.'
                      : 'OpenAI API key required for voice generation. Configure in Settings tab.'}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="generate" className="flex items-center gap-2">
              <PlayCircle className="w-4 h-4" />
              Generate
            </TabsTrigger>
            <TabsTrigger value="history" className="flex items-center gap-2">
              <Clock className="w-4 h-4" />
              History
            </TabsTrigger>
            <TabsTrigger value="settings" className="flex items-center gap-2">
              <Settings className="w-4 h-4" />
              Settings
            </TabsTrigger>
          </TabsList>

          {/* Generate Tab */}
          <TabsContent value="generate" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Generate New Briefing</CardTitle>
                <CardDescription>
                  Create a podcast-style audio summary with two AI hosts (Sarah and Marcus)
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Briefing Type</Label>
                    <Select
                      value={briefingType}
                      onValueChange={(value) => setBriefingType(value as any)}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="morning_briefing">Morning Agent Briefing</SelectItem>
                        <SelectItem value="project">Project Summary</SelectItem>
                        <SelectItem value="portfolio">Portfolio Overview</SelectItem>
                        <SelectItem value="weekly_summary">Weekly Summary</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {briefingType === 'project' && (
                    <div className="space-y-2">
                      <Label>Select Project</Label>
                      <Select value={selectedProjectId} onValueChange={setSelectedProjectId}>
                        <SelectTrigger>
                          <SelectValue placeholder="Choose a project" />
                        </SelectTrigger>
                        <SelectContent>
                          {projectsData?.map((project: any) => (
                            <SelectItem key={project.id} value={project.id}>
                              {project.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  )}
                </div>

                {/* AI Hosts Preview */}
                <div className="flex items-center gap-4 p-4 bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg border border-purple-100">
                  <div className="w-12 h-12 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full flex items-center justify-center">
                    <Users className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1 space-y-1">
                    <h4 className="font-semibold text-sm">Your AI Podcast Hosts</h4>
                    {briefingType === 'morning_briefing' ? (
                      <div className="flex items-center gap-3 text-xs flex-wrap">
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-purple-100 text-purple-700 border-purple-300">
                            Sarah
                          </Badge>
                          <span className="text-muted-foreground">Host</span>
                        </div>
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-green-100 text-green-700 border-green-300">
                            VRO
                          </Badge>
                          <span className="text-muted-foreground">Value Agent</span>
                        </div>
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-amber-100 text-amber-700 border-amber-300">
                            PMO
                          </Badge>
                          <span className="text-muted-foreground">Delivery Agent</span>
                        </div>
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-blue-100 text-blue-700 border-blue-300">
                            Marcus
                          </Badge>
                          <span className="text-muted-foreground">Executive</span>
                        </div>
                      </div>
                    ) : (
                      <div className="flex items-center gap-3 text-xs">
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-purple-100 text-purple-700 border-purple-300">
                            Sarah
                          </Badge>
                          <span className="text-muted-foreground">PMO Analyst</span>
                        </div>
                        <div className="flex items-center gap-1">
                          <Badge variant="outline" className="bg-blue-100 text-blue-700 border-blue-300">
                            Marcus
                          </Badge>
                          <span className="text-muted-foreground">Executive Coach</span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Voice Briefing Player */}
                {briefingType === 'morning_briefing' && (
                  <VoiceBriefingPlayer
                    type="morning_briefing"
                    projectName="Morning Agent Briefing"
                    agents={selectedAgents}
                  />
                )}

                {selectedProjectId && briefingType === 'project' && (
                  <VoiceBriefingPlayer
                    projectId={selectedProjectId}
                    projectName={projectsData?.find((p: any) => p.id === selectedProjectId)?.name}
                    type={briefingType}
                  />
                )}

                {briefingType === 'weekly_summary' && (
                  <VoiceBriefingPlayer type="weekly_summary" projectName="Weekly Summary" />
                )}

                {briefingType === 'portfolio' && (
                  <VoiceBriefingPlayer type="portfolio" projectName="Portfolio Overview" />
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* History Tab */}
          <TabsContent value="history" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <span>Briefing History</span>
                  <Button variant="outline" size="sm" onClick={() => refetchBriefings()}>
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Refresh
                  </Button>
                </CardTitle>
                <CardDescription>
                  View and manage previously generated voice briefings
                </CardDescription>
              </CardHeader>
              <CardContent>
                {!briefingsData?.briefings || briefingsData.briefings.length === 0 ? (
                  <div className="text-center py-12 text-muted-foreground">
                    <Mic className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <p>No briefings generated yet</p>
                    <p className="text-sm mt-1">Generate your first briefing in the Generate tab</p>
                  </div>
                ) : (
                  <div className="border rounded-lg">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Type</TableHead>
                          <TableHead>Project/Topic</TableHead>
                          <TableHead>Duration</TableHead>
                          <TableHead>Generated</TableHead>
                          <TableHead className="text-right">Actions</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {briefingsData.briefings.map((briefing: Briefing) => (
                          <TableRow key={briefing.id}>
                            <TableCell>
                              <Badge variant="outline">
                                {briefing.type.replace('_', ' ')}
                              </Badge>
                            </TableCell>
                            <TableCell className="font-medium">
                              {briefing.projectName || 'N/A'}
                            </TableCell>
                            <TableCell>
                              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                <Clock className="w-3 h-3" />
                                {Math.floor(briefing.duration / 60)}:{String(briefing.duration % 60).padStart(2, '0')}
                              </div>
                            </TableCell>
                            <TableCell className="text-sm text-muted-foreground">
                              {format(new Date(briefing.createdAt), 'MMM d, yyyy HH:mm')}
                            </TableCell>
                            <TableCell className="text-right">
                              <div className="flex items-center justify-end gap-2">
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => window.open(briefing.audioUrl, '_blank')}
                                >
                                  <PlayCircle className="w-4 h-4" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => {
                                    const link = document.createElement('a');
                                    link.href = briefing.audioUrl;
                                    link.download = `briefing-${briefing.id}.mp3`;
                                    link.click();
                                  }}
                                >
                                  <Download className="w-4 h-4" />
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => handleDeleteBriefing(briefing.id)}
                                >
                                  <Trash2 className="w-4 h-4 text-red-500" />
                                </Button>
                              </div>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Settings Tab */}
          <TabsContent value="settings" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Voice Briefing Configuration</CardTitle>
                <CardDescription>
                  Configure OpenAI TTS settings and preferences
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* API Configuration */}
                <div className="space-y-4">
                  <div>
                    <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
                      <Key className="w-4 h-4" />
                      API Configuration
                    </h4>
                    <div className="space-y-3">
                      <div className="space-y-2">
                        <Label>OpenAI API Key</Label>
                        <div className="flex gap-2">
                          <Input
                            type="password"
                            placeholder="sk-..."
                            value={settings.openaiApiKey}
                            onChange={(e) =>
                              setSettings({ ...settings, openaiApiKey: e.target.value })
                            }
                            className="font-mono text-sm"
                          />
                          <Button variant="outline" size="sm">
                            Test
                          </Button>
                        </div>
                        <p className="text-xs text-muted-foreground">
                          Required for generating voice audio. Get your API key from{' '}
                          <a
                            href="https://platform.openai.com/api-keys"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary hover:underline"
                          >
                            OpenAI Platform
                          </a>
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Voice Preferences */}
                  <div className="border-t pt-4">
                    <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
                      <Users className="w-4 h-4" />
                      Voice Preferences
                    </h4>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Default Voice (Marcus)</Label>
                        <Select
                          value={settings.defaultVoice}
                          onValueChange={(value) =>
                            setSettings({ ...settings, defaultVoice: value as any })
                          }
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="alloy">Alloy</SelectItem>
                            <SelectItem value="echo">Echo</SelectItem>
                            <SelectItem value="fable">Fable</SelectItem>
                            <SelectItem value="onyx">Onyx (Default)</SelectItem>
                            <SelectItem value="nova">Nova</SelectItem>
                            <SelectItem value="shimmer">Shimmer</SelectItem>
                          </SelectContent>
                        </Select>
                        <p className="text-xs text-muted-foreground">
                          Sarah always uses Nova voice
                        </p>
                      </div>

                      <div className="space-y-2">
                        <Label>Speaking Speed</Label>
                        <Select
                          value={settings.speakingSpeed.toString()}
                          onValueChange={(value) =>
                            setSettings({ ...settings, speakingSpeed: parseFloat(value) })
                          }
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="0.75">0.75x (Slower)</SelectItem>
                            <SelectItem value="1.0">1.0x (Normal)</SelectItem>
                            <SelectItem value="1.25">1.25x (Faster)</SelectItem>
                            <SelectItem value="1.5">1.5x (Very Fast)</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </div>

                  {/* Automation Settings */}
                  <div className="border-t pt-4">
                    <h4 className="text-sm font-semibold mb-3">Automation</h4>
                    <div className="space-y-3">
                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={settings.autoGenerateDaily}
                          onChange={(e) =>
                            setSettings({ ...settings, autoGenerateDaily: e.target.checked })
                          }
                          className="w-4 h-4 rounded"
                        />
                        <div>
                          <div className="text-sm font-medium">Auto-generate daily briefings</div>
                          <div className="text-xs text-muted-foreground">
                            Automatically create weekly summaries every Monday at 8 AM
                          </div>
                        </div>
                      </label>

                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={settings.notifyOnComplete}
                          onChange={(e) =>
                            setSettings({ ...settings, notifyOnComplete: e.target.checked })
                          }
                          className="w-4 h-4 rounded"
                        />
                        <div>
                          <div className="text-sm font-medium">Notify on completion</div>
                          <div className="text-xs text-muted-foreground">
                            Send notification when briefing generation is complete
                          </div>
                        </div>
                      </label>
                    </div>
                  </div>
                </div>

                <Button onClick={handleSaveSettings} className="w-full">
                  Save Settings
                </Button>
              </CardContent>
            </Card>

            {/* Usage Info */}
            <Card>
              <CardHeader>
                <CardTitle className="text-sm">About Voice Briefings</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm text-muted-foreground">
                <p>
                  Voice briefings use OpenAI's text-to-speech (TTS) API to generate natural-sounding podcast-style summaries.
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Estimated cost: $0.015 per minute of audio (~$0.05 per briefing)</li>
                  <li>Generation time: 10-15 seconds per briefing</li>
                  <li>Two AI hosts: Sarah (PMO Analyst) and Marcus (Executive Coach)</li>
                  <li>Supports project summaries, portfolio overviews, and weekly reports</li>
                </ul>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </AdminLayout>
  );
}
