import * as fs from 'fs';
import * as path from 'path';

const templatesDir = path.join(process.cwd(), 'attached_assets', 'project_templates');

const allStoryCriteria: Record<string, string[]> = {
  // ========== DIGITAL ONBOARDING REDESIGN ==========
  'Progressive Form Architecture': [
    'Given customer starts onboarding, When multi-step form loads, Then progress indicator shows current step with estimated completion time',
    'Given customer abandons mid-flow, When session restored, Then form state persists with data pre-populated from last interaction',
    'Given inline validation fails, When error displayed, Then specific guidance shows with example of correct input format'
  ],
  'Smart Address Lookup': [
    'Given customer enters postcode, When PostCode Anywhere API queried, Then address list returns within 2 seconds for selection',
    'Given address selected, When verified, Then UPRN lookup confirms delivery point accuracy',
    'Given address not found, When manual entry allowed, Then address components captured with Royal Mail PAF validation'
  ],
  'Mobile Responsive Design': [
    'Given customer uses mobile device, When form loads, Then touch-friendly inputs sized for finger interaction',
    'Given slow 3G connection detected, When content loaded, Then progressive enhancement delivers core functionality first',
    'Given device matrix testing runs, When results reviewed, Then 95%+ of target devices pass visual and functional tests'
  ],
  'Document Capture UI': [
    'Given customer uses smartphone camera, When document photographed, Then auto-crop and brightness adjustment applied',
    'Given document image unclear, When quality check fails, Then re-capture prompt with lighting guidance displayed',
    'Given document captured successfully, When OCR runs, Then key data extracted with 95%+ accuracy for ID documents'
  ],
  'Biometric Verification': [
    'Given customer selfie required, When liveness check runs, Then presentation attack detection prevents spoofing with 99%+ accuracy',
    'Given face match required, When compared to ID photo, Then match confidence score returned with pass/fail threshold',
    'Given verification fails, When escalated, Then manual review queue receives case with specific failure reason'
  ],
  'AML/KYC Integration': [
    'Given customer identity verified, When sanctions screening runs, Then PEP and sanctions matches flagged within 30 seconds',
    'Given adverse media check required, When search runs, Then relevant news articles summarized with risk assessment',
    'Given enhanced due diligence triggered, When additional questions displayed, Then customer can complete or schedule callback'
  ],
  'E-Signature Integration': [
    'Given terms acceptance required, When e-signature captured, Then legally binding signature stored with audit trail',
    'Given wet signature required by regulation, When document generated, Then print-sign-scan workflow instructions displayed',
    'Given signature validation fails, When rejected, Then specific issue identified with re-signature guidance'
  ],

  // ========== LONGEVITY MODEL ENHANCEMENT ==========
  'Deprivation Index Integration': [
    'Given member postcode provided, When ONS IMD lookup runs, Then socioeconomic deprivation decile assigned with data currency indicator',
    'Given deprivation index updated by ONS, When new data released, Then lookup tables refresh within 1 month of publication',
    'Given postcode not found, When fallback applied, Then regional average assigned with data quality flag'
  ],
  'Occupation-Based Adjustments': [
    'Given member occupation provided, When SOC code matched, Then occupation-based mortality adjustment factor applied',
    'Given occupation description ambiguous, When classification uncertain, Then default to general population rates with uncertainty margin',
    'Given occupation mortality factor calculated, When applied to base table, Then adjusted qx rates generated by age band'
  ],
  'Lifestyle Factor Model': [
    'Given lifestyle questionnaire completed, When risk factors assessed, Then composite lifestyle score calculated',
    'Given smoking status disclosed, When mortality loading applied, Then extra mortality calculated per underwriting guidelines',
    'Given lifestyle factors change, When recalculated, Then updated mortality expectation reflects latest information'
  ],
  'XGBoost Mortality Model': [
    'Given individual characteristics input, When XGBoost model predicts, Then mortality probability generated with feature importance',
    'Given model prediction made, When explainability requested, Then SHAP values show contribution of each feature',
    'Given model performance monitored, When A/E ratio drifts, Then model retraining triggered with updated data'
  ],
  'Lee-Carter Implementation': [
    'Given historical mortality rates available, When Lee-Carter model fitted, Then age and period parameters estimated with confidence intervals',
    'Given mortality projection required, When model forecasts, Then future mortality rates projected with uncertainty bounds',
    'Given alternative projection models compared, When CBD model also run, Then both projections displayed for actuarial judgement'
  ],
  'Cohort Effect Engine': [
    'Given birth cohort identified, When cohort effect calculated, Then generation-specific mortality adjustment applied',
    'Given cohort effect research updated, When new academic findings published, Then model parameters reviewed within 6 months',
    'Given cohort effect significance tested, When statistical test runs, Then inclusion/exclusion decision documented with rationale'
  ],
  'Longevity Risk Dashboard': [
    'Given portfolio mortality experience reviewed, When A/E analysis runs, Then actual vs expected deaths displayed by age and gender',
    'Given longevity stress test required, When 99.5th percentile scenario applied, Then reserve impact quantified in million pounds',
    'Given longevity swap hedge considered, When priced, Then risk transfer benefit calculated against swap premium'
  ],

  // ========== NET ZERO HOUSING TRACKER ==========
  'Smart Meter Integration': [
    'Given property has smart meter, When API connection established, Then half-hourly consumption data ingested automatically',
    'Given meter data gaps detected, When flagged, Then estimation methodology applied with data quality indicator',
    'Given consumption anomaly detected, When alert triggered, Then property manager notified with investigation guidance'
  ],
  'Consumption Dashboard': [
    'Given property consumption accessed, When dashboard loads, Then electricity, gas, and water usage displayed with benchmarks',
    'Given tenant wants to see usage, When portal accessed, Then personalized consumption insights with cost estimates shown',
    'Given consumption exceeds threshold, When alert created, Then energy efficiency recommendations provided'
  ],
  'Carbon Baseline Calculator': [
    'Given building energy data collected, When carbon calculation runs, Then tCO2e calculated using latest DEFRA conversion factors',
    'Given portfolio carbon footprint aggregated, When reported, Then emissions by source (electricity, gas, vehicles) displayed',
    'Given carbon intensity benchmarked, When compared to sector, Then CRREM alignment score calculated'
  ],
  'Retrofit Scenario Modeling': [
    'Given property requires energy upgrade, When retrofit options modeled, Then EPC improvement, carbon savings, and cost displayed per measure',
    'Given cost-benefit analysis run, When payback calculated, Then NPV of energy savings vs capital cost shown with IRR',
    'Given retrofit package selected, When approved, Then project created with milestones and contractor procurement workflow'
  ],

  // ========== INVESTMENT RESEARCH AI ==========
  'Earnings Transcription': [
    'Given earnings call audio available, When Whisper ASR processes, Then transcript generated with speaker diarization and 98%+ accuracy',
    'Given multiple languages detected, When translation runs, Then English transcript with original language preserved for verification',
    'Given transcript quality reviewed, When corrections made, Then fine-tuning dataset updated for model improvement'
  ],
  'Call Summarization': [
    'Given earnings transcript available, When summarization LLM runs, Then executive summary, key metrics, and guidance extracted',
    'Given sector-specific terminology used, When domain model applied, Then financial terms correctly interpreted with context',
    'Given summary generated, When reviewed by analyst, Then feedback loop improves future summaries'
  ],
  'Management Sentiment': [
    'Given management commentary analyzed, When sentiment classified, Then positive/negative/neutral score calculated with confidence',
    'Given sentiment compared to prior calls, When trend displayed, Then sentiment shift direction and magnitude shown',
    'Given significant sentiment change detected, When alert triggered, Then analyst notified with key phrase excerpts'
  ],
  'Competitive Intelligence': [
    'Given competitor mentions extracted, When analyzed, Then market positioning statements categorized and tracked',
    'Given competitive landscape changes, When detected, Then investment thesis impact assessment provided',
    'Given peer company earnings analyzed, When compared, Then cross-company theme extraction highlights sector trends'
  ],
  'Research Brief Generator': [
    'Given analysis completed, When brief generated, Then MiFID II compliant document produced with disclosures',
    'Given target price updated, When published, Then previous target and rationale history maintained',
    'Given brief distributed, When client access logged, Then research budget allocation tracking updated'
  ],

  // ========== REGULATORY CHANGE MANAGEMENT ==========
  'Regulatory Scanning Service': [
    'Given FCA/PRA publishes new guidance, When scanned, Then relevance assessment generated with affected business areas flagged',
    'Given consultation paper published, When analyzed, Then key proposals summarized with response deadline tracked',
    'Given regulatory deadline approaching, When 90 days out, Then escalation notification sent to compliance and business owners'
  ],
  'Impact Assessment Tracker': [
    'Given regulatory change identified, When impact assessed, Then effort score and resource estimate calculated',
    'Given high impact change identified, When escalated, Then steering committee update scheduled within 2 weeks',
    'Given impact assessment complete, When signed off, Then implementation plan with milestones created'
  ],
  'Policy Update Workflow': [
    'Given internal policy update required, When draft created, Then version control maintains edit history with comparison',
    'Given policy update approved, When published, Then affected staff notified with attestation requirement',
    'Given attestation outstanding, When 14 days elapsed, Then escalation to line manager triggered'
  ],
  'Compliance Dashboard': [
    'Given regulatory portfolio accessed, When dashboard loads, Then implementation status, RAG, and issues displayed',
    'Given implementation delay identified, When escalated, Then contingency plan presented to project sponsor',
    'Given implementation complete, When signed off, Then regulatory compliance confirmation documented'
  ],
  'Training Content Generator': [
    'Given regulatory change requires training, When content created, Then LMS course published with target audience',
    'Given training completion tracked, When threshold met, Then compliance certification updated',
    'Given completion rate below target, When 30 days remain, Then manager notification for non-completers sent'
  ],

  // ========== RISK APPETITE DASHBOARD UPGRADE ==========
  'Risk Data Aggregation': [
    'Given risk metrics calculated across BUs, When aggregated, Then group-level risk profile displayed with drill-down',
    'Given risk metric breaches threshold, When alert triggers, Then risk owner and second line notified within 1 hour',
    'Given risk trend analyzed, When deterioration detected, Then early warning indicator displays with contributing factors'
  ],
  'Threshold Configuration': [
    'Given risk appetite thresholds defined by board, When configured, Then green/amber/red bands applied to metrics',
    'Given appetite reviewed annually, When updated, Then new thresholds effective from specified date with historical comparison',
    'Given metric approaches amber, When 90% reached, Then watching brief notification sent to risk team'
  ],
  'Executive Reporting': [
    'Given quarterly board report due, When generated, Then executive summary with key risk indicators produced',
    'Given emerging risk identified, When documented, Then emerging risk register updated with assessment',
    'Given regulatory risk report required, When data extracted, Then PRA-compliant submission format generated'
  ],
  'Stress Scenario Engine': [
    'Given stress scenario defined, When applied to portfolio, Then capital impact and solvency under stress displayed',
    'Given reverse stress test required, When run, Then scenarios causing failure identified with probabilities',
    'Given stress test results approved, When submitted, Then regulator receives within required timeframe'
  ],

  // ========== SAVINGS INVESTMENTS PLATFORM ==========
  'ISA Product Engine': [
    'Given new ISA product launched, When configured, Then contribution limits and tax wrapper rules applied',
    'Given product fee schedule updated, When published, Then platform charges displayed to customers',
    'Given product withdrawn from sale, When configured, Then existing customers continue but new applications blocked'
  ],
  'Fund Switch Manager': [
    'Given customer places fund trade, When order submitted, Then trade executed at next valuation point with confirmation',
    'Given regular investment scheduled, When payment received, Then automated trade placed with no additional instruction',
    'Given fund switch requested, When processed, Then sell followed by buy with no cash drag between'
  ],
  'Tax Wrapper Compliance': [
    'Given ISA subscription made, When recorded, Then contribution tracked against annual allowance with warning at 90%',
    'Given customer exceeds ISA allowance, When detected, Then excess identified and void ISA rules applied',
    'Given bed and ISA requested, When processed, Then CGT event crystallized and repurchase within wrapper completed'
  ],
  'Valuation Reporting': [
    'Given customer requests valuation, When generated, Then holdings, cost basis, and current value displayed',
    'Given tax year-end consolidation due, When processed, Then CGT summary and dividend reports generated',
    'Given platform statement due, When generated, Then annual summary with charges and performance sent'
  ],
  'Drawdown Calculator': [
    'Given customer in drawdown, When income requested, Then tax-free cash and taxable income calculated per LTA',
    'Given UFPLS withdrawal requested, When processed, Then 25% tax-free and 75% taxable portions calculated',
    'Given death benefit claim made, When processed, Then beneficiary options presented based on member age'
  ],

  // ========== PRIVATE MARKETS PLATFORM ==========
  'Fund NAV Aggregation': [
    'Given PE fund reports quarterly, When NAV data ingested, Then fund metrics update with data currency indicator',
    'Given infrastructure fund has underlying assets, When look-through applied, Then asset-level exposures displayed',
    'Given fund manager provides document, When parsed, Then key data extracted with audit trail to source'
  ],
  'Performance Attribution': [
    'Given private markets performance measured, When IRR/MOIC calculated, Then returns since inception displayed',
    'Given cashflow data received, When PME analysis runs, Then public market equivalent comparison generated',
    'Given attribution required, When analysis runs, Then value creation decomposed by leverage, growth, multiple'
  ],
  'Capital Tracking': [
    'Given capital commitment made, When recorded, Then unfunded commitment tracked with drawdown schedule',
    'Given capital call received, When processed, Then commitment balance updated with payment instruction',
    'Given distribution received, When recorded, Then DPI and RVPI metrics updated with waterfall analysis'
  ],
  'Portfolio Analytics': [
    'Given private markets portfolio accessed, When dashboard loads, Then allocation by strategy and vintage displayed',
    'Given ESG data available, When aggregated, Then portfolio-level ESG scores calculated',
    'Given liquidity projection required, When modeled, Then expected cashflows by quarter for 5 years displayed'
  ],
  'Manager ODD Tracker': [
    'Given fund manager ODD completed, When documented, Then operational risk assessment stored with renewal reminder',
    'Given manager incident reported, When logged, Then exposure quantified and escalation triggered',
    'Given DDQ refresh due, When notification sent, Then manager portal access granted for self-certification'
  ],
  'Secondary Pricing': [
    'Given secondary sale considered, When market analyzed, Then expected pricing range based on transactions displayed',
    'Given bid received, When evaluated, Then discount/premium to NAV calculated with recommendation',
    'Given secondary sale closed, When completed, Then gain/loss calculated with tax reporting data'
  ],
  'Co-Invest Management': [
    'Given co-investment opportunity presented, When evaluated, Then IC materials generated with risk assessment',
    'Given co-investment committed, When tracked, Then valuation updates separate from parent fund',
    'Given co-investment exits, When proceeds received, Then realized return calculated with attribution'
  ],

  // ========== INFRASTRUCTURE ASSET MANAGEMENT ==========
  'Asset Registry': [
    'Given infrastructure asset acquired, When registered, Then valuation, depreciation schedule, and maintenance plan created',
    'Given asset condition assessment due, When completed, Then condition score updated with remaining useful life',
    'Given asset disposal planned, When executed, Then gain/loss calculated with environmental obligations captured'
  ],
  'Performance Tracking': [
    'Given infrastructure asset has contracted revenue, When forecast modeled, Then NPV of future cashflows calculated',
    'Given inflation adjustment applies, When escalator applied, Then real and nominal revenue projections generated',
    'Given regulatory price review approaches, When modeled, Then allowed revenue under scenarios compared'
  ],
  'Maintenance Scheduler': [
    'Given preventive maintenance scheduled, When due date approaches, Then work order generated with contractor notification',
    'Given unplanned maintenance required, When emergency work order created, Then availability and budget impact tracked',
    'Given maintenance history analyzed, When patterns identified, Then predictive maintenance recommendations generated'
  ],
  'Compliance Tracker': [
    'Given insurance renewal due, When notification sent, Then coverage review completed with risk engineering recommendations',
    'Given regulatory inspection completed, When findings logged, Then remediation tracked',
    'Given HSE incident occurs, When reported, Then root cause analysis initiated with RIDDOR compliance checked'
  ],
  'DCF Valuation': [
    'Given infrastructure valuation required, When DCF model runs, Then fair value calculated with key assumptions documented',
    'Given comparable transactions available, When benchmarked, Then valuation multiple comparison provided',
    'Given quarterly valuation due, When completed, Then NAV impact calculated with movement attribution'
  ],

  // ========== PENSION SCHEME DATA HUB ==========
  'Scheme Configuration': [
    'Given new scheme onboarded, When configuration wizard completed, Then scheme rules and benefit structure stored',
    'Given scheme rules amended, When change logged, Then effective date and audit trail maintained with version history',
    'Given scheme merger occurs, When consolidation runs, Then member data migrates with rules mapping'
  ],
  'Member Repository': [
    'Given member record accessed, When display requested, Then full benefit entitlement and service history visible',
    'Given member data change received, When validated, Then record updated with source attribution and timestamp',
    'Given bulk data refresh required, When batch import runs, Then quality report generated with error counts'
  ],
  'Benefit Calculator': [
    'Given member requests quote, When calculation runs, Then pension calculated per scheme rules with assumptions disclosed',
    'Given transfer value requested, When CETV calculated, Then cash equivalent calculated with 3-month guarantee',
    'Given retirement options requested, When commutation applied, Then lump sum and reduced pension displayed'
  ],
  'Payroll Integration': [
    'Given payroll cycle due, When payment file generated, Then BACS file produced with net payments after tax',
    'Given HMRC PAYE codes received, When applied, Then tax deductions calculated with RTI submission generated',
    'Given payment returned unpaid, When identified, Then tracing process initiated with payment re-routing'
  ],
  'Member Portal': [
    'Given member logs into portal, When dashboard loads, Then benefit summary and communication history displayed',
    'Given member requests projection, When calculator accessed, Then estimated pension at different dates shown',
    'Given member updates contact details, When submitted, Then address and email update across integrated systems'
  ],

  // ========== OPERATIONAL RESILIENCE FRAMEWORK ==========
  'IBS Dependency Mapping': [
    'Given Important Business Service identified, When dependency mapping runs, Then upstream and downstream dependencies visualized as network',
    'Given service owner interviewed, When dependencies documented, Then technology, people, process, and third-party captured',
    'Given dependency graph complete, When CMDB integration runs, Then linkages to infrastructure automatically populated'
  ],
  'Impact Tolerance Definition': [
    'Given IBS identified, When impact tolerance workshop conducted, Then maximum tolerable disruption defined with justification',
    'Given impact tolerance breached during incident, When escalation triggers, Then executive notification with remediation initiated',
    'Given regulatory tolerance changes, When updated, Then affected IBS tolerances reviewed within 30 days'
  ],
  'Scenario Library': [
    'Given resilience scenarios required, When library accessed, Then 20 core scenarios covering cyber, supplier, infrastructure available',
    'Given custom scenario needed, When configured, Then scenario parameters and expected impacts captured',
    'Given scenario executed, When results recorded, Then evidence and learnings stored for regulatory reporting'
  ],
  'Test Execution Framework': [
    'Given scenario test scheduled, When orchestration runs, Then simulated disruption introduced with rollback capability',
    'Given test evidence captured, When review completed, Then gaps identified with remediation actions',
    'Given regulatory reporting due, When ICARA extract generated, Then PRA-compliant self-assessment produced'
  ],
  'Vendor Dependency Register': [
    'Given third-party provides critical service, When onboarded, Then concentration risk and exit strategy documented',
    'Given vendor risk score calculated, When threshold breached, Then enhanced due diligence triggered',
    'Given vendor incident occurs, When logged, Then IBS impact assessed and reported if material'
  ],
  'Concentration Risk Dashboard': [
    'Given third-party dependencies aggregated, When analyzed, Then single points of failure identified',
    'Given concentration mitigation required, When alternative assessed, Then transition plan documented',
    'Given regulatory inquiry received, When report generated, Then PRA/FCA-ready documentation produced within 5 days'
  ],
  'Recovery Time Objectives': [
    'Given IBS has defined RTO, When tested, Then actual recovery time measured against target with variance documented',
    'Given RTO consistently missed, When escalated, Then improvement plan with investment presented to exec',
    'Given technology change affects recovery, When assessed, Then updated RTO validated before go-live'
  ],

  // ========== CLIMATE TRANSITION ANALYTICS ==========
  'NGFS Scenario Implementation': [
    'Given NGFS scenario version selected, When portfolio analyzed, Then asset-level impact quantified across 2030/2040/2050 horizons',
    'Given NGFS updates parameters, When new version released, Then platform incorporates within 1 month',
    'Given custom scenario defined, When created, Then custom pathway saved and reusable for comparison'
  ],
  'Custom Scenario Builder': [
    'Given custom climate parameters required, When builder accessed, Then carbon price, policy, and technology assumptions configurable',
    'Given scenario preview requested, When calculated, Then real-time portfolio impact updates as parameters change',
    'Given scenario saved, When shared, Then version control and access permissions applied'
  ],
  'Portfolio Stress Testing': [
    'Given climate stress test required, When run, Then VaR and expected shortfall under scenario calculated',
    'Given TCFD report required, When export generated, Then compliant template with all recommended disclosures produced',
    'Given stress results reviewed, When approved, Then results available for regulatory submission'
  ],
  'Implied Temperature Rise Calculation': [
    'Given portfolio holdings provided, When ITR calculated, Then temperature alignment score with methodology disclosed',
    'Given company targets assessed, When credibility scored, Then confidence weighting applied to trajectory',
    'Given ITR drill-down requested, When analyzed, Then top contributors identified with engagement actions'
  ],
  'Physical Risk Mapping': [
    'Given real asset geocoded, When climate hazard layers applied, Then flood/wildfire/heat scores at property level displayed',
    'Given risk score is high, When drill-down requested, Then specific hazards and adaptation recommendations provided',
    'Given physical risk aggregated, When reported, Then VaR contribution from physical vs transition quantified'
  ],
  'Decarbonization Tracker': [
    'Given portfolio carbon baseline established, When target set, Then SBTi-aligned reduction pathway calculated',
    'Given interim target reached, When progress assessed, Then variance quantified with rebalancing options',
    'Given target methodology updates, When recalculated, Then old vs new comparison displayed'
  ],
  'Net Zero Dashboard': [
    'Given Net Zero commitment made, When dashboard accessed, Then current footprint vs target pathway displayed',
    'Given manager drills down, When asset view loaded, Then individual security contribution shown',
    'Given quarterly progress due, When report generated, Then standardized NZAM report exports with disclosures'
  ],

  // ========== ENTERPRISE DATA PLATFORM ==========
  'Azure ADLS Gen2 Infrastructure Setup': [
    'Given infrastructure-as-code is executed, When Terraform applies successfully, Then ADLS Gen2 containers are provisioned with RBAC policies in under 30 minutes',
    'Given storage accounts are created, When hierarchical namespace is enabled, Then Delta Lake tables can be written with ACID transactions',
    'Given disaster recovery is configured, When primary region fails, Then data is accessible from paired region within RPO of 1 hour'
  ],
  'Delta Lake Table Implementation': [
    'Given raw data is ingested into Bronze layer, When Delta format applied, Then time travel queries retrieve data from any point in last 90 days',
    'Given concurrent writes from multiple jobs occur, When ACID transactions complete, Then data integrity is maintained with optimistic concurrency control',
    'Given schema evolution is required, When new columns added via ALTER, Then existing Spark queries continue working with null handling'
  ],
  'Source System Connectors': [
    'Given source system credentials configured, When connector job runs, Then data extracted with CDC for incremental loads',
    'Given API rate limit reached, When throttling detected, Then backoff strategy applies with job resumption without data loss',
    'Given new source onboarding requested, When connector instantiated, Then first data load completes within 2-week sprint'
  ],
  'Data Quality Rules Engine': [
    'Given Great Expectations rules defined, When validation runs, Then DQ results publish to catalog with pass/fail per expectation',
    'Given DQ score falls below 95%, When alert triggers, Then data steward receives notification with failed records sample',
    'Given new DQ rule requested, When configured in YAML, Then rule applies to next validation without code deployment'
  ],
  'Purview Catalog Integration': [
    'Given Databricks notebook processes data, When lineage captured, Then Purview shows full transformation path from source to gold',
    'Given data consumer searches, When query returns results, Then sensitivity labels and data owner contact displayed',
    'Given glossary term updated, When propagated, Then linked technical assets reflect updated context within 1 hour'
  ],
  'PII Detection Service': [
    'Given data lake contains customer records, When Presidio analyzer runs, Then PII entities tagged with 95%+ precision',
    'Given analyst without PII clearance queries data, When dynamic masking applied, Then obfuscated values returned',
    'Given SAR deletion request received, When processed, Then customer PII removed from Bronze/Silver/Gold within 72 hours'
  ],
  'Customer 360 Data Model': [
    'Given customer holds policy across L&G divisions, When entity resolution runs, Then records link under single golden ID with confidence score',
    'Given customer changes address, When update ingested, Then address propagates to 360 view within 1 hour',
    'Given duplicate records identified, When merge executed, Then transaction history consolidates preserving audit trail'
  ],
  'Feature Store Implementation': [
    'Given feature registered in Feast, When ML model requests feature, Then real-time serving returns value in <50ms from Redis',
    'Given feature definition changes, When new version deployed, Then model training uses versioned features with point-in-time correctness',
    'Given feature drift detected, When threshold exceeded, Then alert triggers to data science team'
  ],
  'ML Model Registry': [
    'Given data scientist trains model, When registered in MLflow, Then artifacts, metrics, parameters are versioned and searchable',
    'Given model promoted to production, When deployment triggers, Then A/B traffic split configures champion vs challenger',
    'Given model performance degrades, When retraining runs, Then new version validated against holdout set before promotion'
  ],
  'Data Mesh Domain Setup': [
    'Given business domain identified, When domain team onboarded, Then domain-specific data products published to mesh catalog',
    'Given data product SLA defined, When monitoring enabled, Then freshness and quality metrics tracked with alerting',
    'Given cross-domain access requested, When approved, Then federated query routes to source domain with access logged'
  ],
  'Self-Service Analytics Portal': [
    'Given business analyst accesses portal, When dataset selected, Then Power BI report loads within 5 seconds with row-level security',
    'Given custom analysis needed, When SQL submitted, Then results return from Databricks SQL with cost governance applied',
    'Given report scheduled, When delivery time reached, Then PDF/Excel emailed to distribution list'
  ],
  'Data Governance Workflows': [
    'Given sensitive dataset created, When classification requested, Then data steward workflow initiates with assessment form',
    'Given access request submitted, When approved by owner, Then permissions propagate to Unity Catalog within 15 minutes',
    'Given retention period expires, When archival runs, Then data moved to cold storage with metadata retained'
  ],

  // ========== AI CHATBOT IMPLEMENTATION ==========
  'Intent Classification Model': [
    'Given customer types pension query, When NLU processes, Then intent classified with 92%+ accuracy within 2 seconds',
    'Given ambiguous query with multiple intents, When confidence below threshold, Then clarification question generated',
    'Given new intent pattern emerges, When retraining triggered, Then updated model deploys within 48 hours'
  ],
  'LLM Response Generation': [
    'Given customer question matched to intent, When GPT-4 generates response, Then answer is contextually accurate with pension terminology',
    'Given hallucination risk detected, When confidence low, Then response includes caveat and offers human escalation',
    'Given response generated, When quality scored, Then inappropriate responses trigger feedback loop to content team'
  ],
  'Multi-turn Conversation Management': [
    'Given customer mid-conversation, When context window updated, Then previous exchanges inform current response with slot filling',
    'Given conversation exceeds 10 turns, When summarization triggered, Then key points extracted to maintain context within token limits',
    'Given customer returns after timeout, When conversation resumes, Then previous context restored with recap offered'
  ],
  'Knowledge Base RAG System': [
    'Given pension scheme rules uploaded, When vector embedding created, Then semantic search returns relevant passages in <500ms',
    'Given customer asks scheme-specific question, When RAG retrieves context, Then answer cites source document with confidence score',
    'Given document updated by content team, When re-indexed, Then new content searchable within 4 hours'
  ],
  'Pension Calculator Widget': [
    'Given member requests retirement projection, When calculator invoked, Then illustration uses scheme data with statutory assumptions',
    'Given SMPI illustration required, When generated, Then PDF includes all FCA-mandated disclosures',
    'Given user adjusts retirement age, When projection recalculates, Then impact on pension amount updates in real-time'
  ],
  'Human Handoff System': [
    'Given customer requests human agent, When handoff initiated, Then full transcript transfers to agent CRM',
    'Given chatbot cannot resolve after 3 attempts, When escalation triggers, Then customer informed of queue position and wait time',
    'Given agent accepts handoff, When conversation continues, Then agent has full context without customer repeating'
  ],
  'Compliance Guardrails': [
    'Given question approaches regulated financial advice, When boundary detected, Then chatbot explains limitation and offers FCA adviser referral',
    'Given FCA Consumer Duty updates, When content team refreshes guardrails, Then new rules active within 48 hours',
    'Given compliance audit requested, When logs reviewed, Then triggered guardrails highlighted with timestamps'
  ],
  'Analytics & Reporting Dashboard': [
    'Given chatbot is live, When metrics accessed, Then containment rate, CSAT score, and top intents display in real-time',
    'Given unhandled query pattern identified, When flagged, Then content team receives weekly digest with resolution recommendations',
    'Given A/B test configured, When statistically significant winner determined, Then winning variant auto-promotes'
  ],
  'Web Widget Deployment': [
    'Given website integration required, When widget script embedded, Then chatbot loads within 2 seconds with consistent styling',
    'Given mobile browser detected, When widget rendered, Then responsive design provides optimal touch experience',
    'Given widget loads on authenticated page, When session context passed, Then personalized greeting uses customer name'
  ],
  'IVR Integration': [
    'Given customer calls contact centre, When IVR dialogue triggered, Then voice recognition accuracy exceeds 85% for pension queries',
    'Given speech-to-text transcribes query, When intent matched, Then automated response plays with option to transfer',
    'Given call quality degrades, When audio issues detected, Then graceful fallback offers callback option'
  ],
  'Mobile SDK Integration': [
    'Given mobile app integrates chatbot SDK, When user taps chat icon, Then conversation interface loads natively within 1 second',
    'Given push notification received, When user responds via chat, Then context includes notification reference',
    'Given app is offline, When chat attempted, Then queued messages sync when connectivity restored'
  ],
  'Document Ingestion Pipeline': [
    'Given PDF pension document uploaded, When OCR and parsing complete, Then structured data extracted with 95%+ accuracy',
    'Given document contains tables, When processed, Then tabular data is queryable and charts summarized',
    'Given document language is Welsh, When language detected, Then appropriate language model processes content'
  ],

  // ========== BUILD TO RENT OPERATING PLATFORM ==========
  'Property Listings': [
    'Given property becomes available, When listing created, Then photos, floor plans, and virtual tour publish within 24 hours',
    'Given prospect inquires about listing, When lead captured, Then automated response with booking link sent within 2 hours',
    'Given listing updated, When saved, Then Rightmove/Zoopla syndication reflects changes within 4 hours'
  ],
  'Application Processing': [
    'Given prospective tenant completes application, When ID uploaded, Then biometric liveness check completes in under 60 seconds',
    'Given affordability assessment required, When Open Banking connected, Then 30x rent income verification runs automatically',
    'Given all checks pass, When approval granted, Then AST contract with property-specific terms generates for e-signature'
  ],
  'Referencing Integration': [
    'Given tenant referencing initiated, When request sent to provider, Then credit check and references return within 48 hours',
    'Given referencing returns adverse indicator, When guarantor required, Then guarantor application workflow triggers automatically',
    'Given all references satisfactory, When passed, Then move-in workflow initiates with key collection scheduling'
  ],
  'Tenancy Agreement Generation': [
    'Given tenancy approved, When AST generated, Then all prescribed information per Housing Act 1988/2004 is included',
    'Given deposit calculated, When protected with TDS, Then protection certificate auto-attaches to tenant portal',
    'Given tenant e-signs agreement, When landlord countersigns, Then fully executed copy stores with 7-year retention'
  ],
  'Work Order System': [
    'Given tenant reports emergency, When work order created, Then contractor dispatched within 4-hour emergency SLA',
    'Given contractor completes repair, When photos uploaded, Then tenant receives completion notification with satisfaction survey',
    'Given same issue reported 3 times, When pattern detected, Then property manager escalation flags potential major works'
  ],
  'Contractor Management': [
    'Given contractor onboarded, When compliance check runs, Then public liability, gas safe, and DBS are verified',
    'Given contractor misses SLA, When 24 hours elapsed, Then automated penalty calculation triggers with notification',
    'Given contractor invoice submitted, When validated against work order, Then payment schedules per agreed terms'
  ],
  'Rent Collection': [
    'Given rent due date is 1st of month, When Direct Debit collected, Then payment posts to ledger with automated receipt',
    'Given Direct Debit fails, When arrears status begins, Then SMS and email reminder sent with payment link',
    'Given 7 days arrears threshold reached, When case escalated, Then dedicated arrears officer assigned'
  ],
  'Arrears Management': [
    'Given arrears exceed 500 pounds, When payment plan workflow triggers, Then tenant offered structured repayment options',
    'Given payment plan agreed, When schedule activated, Then automated collections adjust to plan installments',
    'Given pre-action protocol threshold reached, When legal process initiates, Then compliant Section 8 notice generates'
  ],
  'Building Access Control': [
    'Given tenant moves in, When access credentials provisioned, Then fob/app unlocks apartment, parking, and amenities',
    'Given tenant requests guest access, When temporary code generated, Then access valid for specified hours with visitor log',
    'Given lease ends, When tenant checks out, Then all access credentials deactivate within 1 hour of termination'
  ],
  'Move-in/Move-out Inspections': [
    'Given move-in scheduled, When inventory inspection conducted, Then photo evidence captured with standardized condition rating',
    'Given move-out finds damage beyond fair wear, When assessed, Then deposit deduction calculated with itemized breakdown',
    'Given inventory comparison complete, When report finalized, Then tenant receives copy within 7 days with dispute window'
  ],
  'Community Engagement': [
    'Given resident event planned, When invitations distributed via app, Then RSVP tracking enables capacity management',
    'Given tenant requests amenity booking, When availability checked, Then gym/cinema/workspace slot reserved with QR access',
    'Given quarterly satisfaction survey distributed, When responses analyzed, Then NPS trends display per building with actions'
  ],

  // ========== BULK ANNUITY PRICING ENGINE ==========
  'Bloomberg B-PIPE Integration': [
    'Given UK gilt market is open, When yield curve requested, Then data is <5 seconds stale with sub-second API response',
    'Given Bloomberg feed experiences outage, When failover triggers, Then Reuters backup activates with data source audit log',
    'Given quote is generated using market data, When audit trail requested, Then exact timestamp and value of each rate retrievable'
  ],
  'Credit Spread Curve Builder': [
    'Given issuer has investment-grade rating, When credit curve built, Then spreads interpolate across 1-50 year tenors using NSS model',
    'Given new corporate bond trades in secondary market, When price observed, Then curve recalibrates within 1 hour',
    'Given odd maturity tenor requested, When interpolation applied, Then cubic spline provides arbitrage-free smooth transition'
  ],
  'Swap Rate Integration': [
    'Given interest rate swap tenor selected, When live rate queried, Then ICE mid-market rate returned in <100ms',
    'Given historical swap rate analysis needed, When 10-year lookback requested, Then intraday granularity time series available',
    'Given cross-currency basis swap adjustment required, When SOFR-SONIA basis applied, Then spread adjustment incorporated'
  ],
  'Historical Deal Data Pipeline': [
    'Given 10+ years of closed BPA deals exist, When data cleaned, Then 2,500+ deals available for ML training with consistent encoding',
    'Given data quality issue identified, When flagged, Then manual review queue receives case with specific field highlighted',
    'Given new deal closes successfully, When deal data ingested, Then ML model retraining pipeline triggers within 24 hours'
  ],
  'Win Probability Model': [
    'Given deal parameters entered, When XGBoost model predicts, Then win probability 0-100% returned with 90% confidence interval',
    'Given prediction made and deal outcome known, When accuracy tracked, Then Brier score and calibration curve update',
    'Given macro conditions shift significantly, When model retrained, Then performance improvement validated on holdout set'
  ],
  'Optimal Pricing Recommendation': [
    'Given target margin and win probability trade-off defined, When optimization runs, Then price recommendation balances profitability with positioning',
    'Given competitive intelligence on rival pricing available, When incorporated, Then recommendations adjust based on competitor behavior',
    'Given pricing recommendation reviewed by actuary, When rationale requested, Then SHAP values explain contribution of each feature'
  ],
  'Quote Generation Engine': [
    'Given liability cashflows uploaded for 10,000 members, When pricing engine invoked, Then quote generation completes in under 60 seconds',
    'Given market conditions change mid-morning, When re-quote triggered, Then updated price reflects latest gilt yields and credit spreads',
    'Given final quote approved, When documentation packaged, Then full assumptions breakdown and sensitivity tables are audit-ready'
  ],
  'Model Explainability Dashboard': [
    'Given ML pricing model makes recommendation, When explainability requested, Then feature importance and SHAP charts display',
    'Given model governance review is due, When documentation generated, Then model card with training summary and limitations produced',
    'Given prediction differs from actuarial judgement, When investigated, Then model factors driving deviation clearly identified'
  ],
  'Sensitivity Analysis Tools': [
    'Given base case quote generated, When sensitivity analysis initiated, Then impact of +/-50bps gilt yield shift calculated and displayed',
    'Given mortality improvement assumption varied, When scenario runs, Then liability impact in million pounds quantified with chart',
    'Given multiple scenarios requested, When batch processed, Then comparison table with tornado diagram generated'
  ],

  // ========== ESG ANALYTICS DASHBOARD ==========
  'MSCI ESG Ratings Integration': [
    'Given MSCI publishes daily ESG rating update, When feed processed overnight, Then updated ratings reflect in portfolio scores by market open',
    'Given portfolio contains 500+ securities, When MSCI coverage analyzed, Then percentage covered and gaps by sector reported',
    'Given MSCI methodology version changes, When new methodology released, Then recalibration impact analysis available within 1 week'
  ],
  'Sustainalytics Risk Scores': [
    'Given company experiences ESG controversy, When Sustainalytics updates severity, Then alert triggers to portfolio managers with exposure quantified',
    'Given company ESG Risk Rating deteriorates to High, When threshold breach detected, Then watchlist notification includes controversy details',
    'Given controversy status changes to resolved, When database updated, Then historical timeline displays full lifecycle'
  ],
  'Climate Data Pipeline': [
    'Given CDP releases annual climate questionnaire, When data ingested, Then company climate scores available within 48 hours',
    'Given company reports Scope 1/2/3 GHG emissions, When data normalized to tCO2e per million pounds revenue, Then peer comparison enabled',
    'Given company sets SBTi-validated target, When SBTi database syncs, Then Net Zero commitment status reflects within 1 week'
  ],
  'SFDR PAI Reporting': [
    'Given Article 8 fund selected for PAI disclosure, When report generates, Then all 18 mandatory PAI indicators calculated with coverage displayed',
    'Given PAI data gaps exist, When estimation methodology applied, Then estimation approach disclosed per SFDR RTS requirements',
    'Given PAI indicator values calculated, When benchmarked against peer funds, Then relative performance displays with traffic light status'
  ],
  'EU Taxonomy Alignment Engine': [
    'Given company discloses Taxonomy-eligible activities, When alignment assessed, Then DNSH criteria status shown for each of 6 environmental objectives',
    'Given company Taxonomy disclosure is incomplete, When alignment calculated, Then estimation methodology and data sources disclosed',
    'Given EU Taxonomy Delegated Acts updated, When regulatory change implemented, Then technical screening criteria reflect new thresholds within 2 months'
  ],
  'Portfolio Carbon Calculator': [
    'Given portfolio holdings with weights provided, When WACI calculated, Then weighted average carbon intensity displayed with sector attribution',
    'Given Net Zero 2050 target commitment exists, When decarbonization trajectory modeled, Then year-by-year interim target pathway shown',
    'Given carbon attribution drill-down requested, When analysis runs, Then top 10 carbon contributors identified with engagement priority ranking'
  ],
  'TCFD Scenario Analysis': [
    'Given NGFS climate scenarios selected, When portfolio stress test runs, Then value at risk impact quantified across time horizons',
    'Given physical risk assessment needed for real assets, When geocoding complete, Then flood/wildfire/heat stress scores display at asset level',
    'Given transition risk from carbon pricing modeled, When carbon price pathway applied, Then stranded asset exposure calculated'
  ],

  // ========== CLIENT PORTAL MODERNIZATION ==========
  'Portfolio Summary View': [
    'Given institutional client logs into portal, When portfolio dashboard loads, Then AUM, asset allocation, and performance display within 3 seconds',
    'Given portfolio has multiple mandates, When summary expanded, Then individual mandate cards show with performance vs benchmark',
    'Given client wants PDF report, When export triggered, Then branded client report downloads with current as-of date'
  ],
  'Performance Attribution Analysis': [
    'Given client selects mandate for attribution, When Brinson model runs, Then allocation, selection, and interaction effects display by sector',
    'Given attribution period selected, When analysis runs, Then cumulative and period attribution charts generate',
    'Given benchmark change occurred mid-period, When handled, Then attribution correctly segments before/after with composite benchmark'
  ],
  'Risk Metrics Dashboard': [
    'Given client requests risk analytics, When dashboard loads, Then VaR, tracking error, and Sharpe ratio display with confidence intervals',
    'Given risk limit breach occurs, When detected, Then breach notification sent to client relationship manager within 1 hour',
    'Given stress scenario selected, When stress test runs, Then portfolio impact displays with position-level decomposition'
  ],
  'Cash Movement Requests': [
    'Given client initiates cash withdrawal, When request submitted, Then dual authorization workflow triggers with limit validation',
    'Given cash movement exceeds threshold, When escalation required, Then senior approval step added with SLA tracking',
    'Given cash movement approved, When scheduled, Then execution date confirmed with settlement instructions'
  ],
  'Rebalancing Requests': [
    'Given client requests portfolio rebalancing, When submitted, Then IPS compliance check runs automatically',
    'Given rebalancing violates IPS constraint, When detected, Then request flagged with constraint violation details',
    'Given rebalancing approved, When executed, Then trade blotter updates with execution details and TCA report'
  ],
  'Document Repository': [
    'Given client needs historical documents, When document library accessed, Then contracts, reports, and statements are searchable by date and type',
    'Given new quarterly report published, When uploaded, Then client notification sent with secure download link',
    'Given document retention period expires, When archival runs, Then document moved to cold storage per data retention policy'
  ],

  // ========== CLIMATE TRANSITION ANALYTICS ==========
  'NGFS Scenario Implementation': [
    'Given NGFS scenario version selected (orderly/disorderly/hot house), When portfolio analyzed, Then asset-level impact quantified across 2030/2040/2050 horizons',
    'Given NGFS updates scenario parameters, When new version released, Then platform incorporates updated parameters within 1 month',
    'Given custom scenario parameters defined, When scenario created, Then custom pathway can be saved and reused for comparison'
  ],
  'Implied Temperature Rise Calculation': [
    'Given portfolio holdings provided, When ITR calculated, Then portfolio temperature alignment score displays with methodology disclosure',
    'Given company targets assessed, When credibility scored, Then high/medium/low confidence weighting applied to trajectory',
    'Given ITR drill-down requested, When analysis runs, Then top 10 temperature contributors identified with engagement actions'
  ],
  'Physical Risk Mapping': [
    'Given real asset portfolio geocoded, When climate hazard layers applied, Then flood/wildfire/heat/water stress scores display at property level',
    'Given physical risk score is high, When drill-down requested, Then specific hazards and adaptation recommendations provided',
    'Given portfolio physical risk aggregated, When reported, Then VaR contribution from physical risk quantified vs transition risk'
  ],
  'Transition Pathway Tracker': [
    'Given company publishes Net Zero commitment, When tracked, Then interim targets and progress milestones monitored with alerts on missed targets',
    'Given sector decarbonization pathway defined, When company compared, Then alignment vs Paris-aligned trajectory scored',
    'Given company transition plan published, When assessed, Then credibility scoring reflects CapEx commitment and technology roadmap'
  ],
  'Decarbonization Target Setting': [
    'Given portfolio carbon intensity baseline established, When target set, Then SBTi-aligned reduction pathway calculated',
    'Given interim target year reached, When progress assessed, Then variance from target quantified with rebalancing options',
    'Given target methodology updates, When recalculated, Then comparison between old and new methodology results displayed'
  ],
  'Net Zero Progress Dashboard': [
    'Given Net Zero commitment made, When dashboard accessed, Then current carbon footprint vs target pathway displays',
    'Given portfolio manager drills down, When asset-level view loaded, Then individual security contribution to carbon reduction shown',
    'Given quarterly progress report due, When generated, Then standardized NZAM progress report exports with required disclosures'
  ],
  'Stranded Asset Risk Analysis': [
    'Given fossil fuel exposure assessed, When stranded asset risk calculated, Then value at risk under accelerated phase-out scenario quantified',
    'Given sector-specific transition risk modeled, When results displayed, Then oil and gas, utilities, transport sectors analyzed separately',
    'Given engagement priority needed, When ranked, Then companies with highest stranding risk and engagement opportunity flagged'
  ],

  // ========== PROTECTION PRODUCT DIGITIZATION ==========
  'Product Selector': [
    'Given customer answers lifestyle and protection needs questions, When recommendation engine runs, Then suitable life/CI/IP products ranked with coverage rationale',
    'Given customer specifies monthly budget, When products filtered, Then affordable alternatives presented with trade-off explanations',
    'Given customer discloses dependents and mortgage, When sum assured calculated, Then recommendation accounts for income replacement and debt clearance'
  ],
  'Quote Engine': [
    'Given customer enters details and coverage requirements, When quote calculation runs, Then premium displays within 5 seconds with breakdown',
    'Given customer discloses smoker status or elevated BMI, When rating factors applied, Then premium loading explained with wellness discount opportunities',
    'Given customer saves quote for later, When returning within 30 days, Then quote retrievable with option to refresh rates'
  ],
  'Underwriting Rules Engine': [
    'Given application submitted through digital journey, When rules evaluate, Then 65%+ receive straight-through processing without referral',
    'Given medical condition disclosed, When decision tree followed, Then appropriate outcome automated per underwriting manual',
    'Given edge case triggers referral, When case appears in queue, Then pre-populated risk assessment and recommended decision displayed'
  ],
  'Medical Evidence Gateway': [
    'Given GP report required, When eMRO electronic request sent, Then medical records received within average 10 business days',
    'Given tele-underwriting interview needed, When scheduled, Then customer books time slot via SMS booking link',
    'Given all medical evidence reviewed, When final decision made, Then decision letter with explanation sent within 48 hours'
  ],
  'Policy Issuance': [
    'Given application approved and premium paid, When policy documents generated, Then policy schedule and terms available in secure portal',
    'Given customer requests mid-term alteration, When change processed, Then premium recalculates with pro-rata adjustment',
    'Given annual renewal approaches, When renewal notice sent, Then customer can confirm, adjust, or cancel online'
  ],
  'Claims Journey': [
    'Given claim initiated via portal or phone, When FNOL received, Then acknowledgment with expected timeline sent within 2 hours',
    'Given supporting evidence uploaded, When claims assessor reviews, Then decision made within 5 business days for straightforward claims',
    'Given claim approved for payment, When funds released, Then payment reaches claimant within 3 business days with confirmation'
  ],

  // ========== PRT INTAKE SYSTEM ==========
  'Multi-Format Parser': [
    'Given pension scheme provides member data in Excel, When file uploaded, Then 50,000+ records parsed within 5 minutes with validation report',
    'Given scheme uses legacy column headers, When intelligent mapping runs, Then field suggestions achieve 90%+ accuracy with manual override',
    'Given file contains duplicate NI numbers, When duplicates detected, Then records flagged with merge/split decision workflow'
  ],
  'Data Validation Rules': [
    'Given member data batch ingested, When 200+ validation rules execute, Then errors categorized with correction guidance per field',
    'Given NI number format validation fails, When error displayed, Then correct format example and common mistakes shown',
    'Given benefit calculation validation detects discrepancy, When flagged, Then expected vs actual values displayed with calculation breakdown'
  ],
  'Data Cleansing Workflows': [
    'Given multiple validation errors exist, When cleansing UI accessed, Then batch editing allows simultaneous correction of common patterns',
    'Given address is incomplete, When Royal Mail PAF lookup triggered, Then address auto-completes from postcode with UPRN validation',
    'Given cleansing session complete, When sign-off requested, Then audit trail captures all changes with user attribution and timestamp'
  ],
  'GMP Calculation Engine': [
    'Given member has GMP entitlement, When GMP calculated at payment age, Then correct revaluation method applied based on leaving date',
    'Given HMRC GMP reconciliation required, When COD statement received, Then variance report generated with explanation codes per discrepancy',
    'Given GMP equalisation applies per Lloyds ruling, When conversion method selected, Then calculation implements methodology per actuarial guidance'
  ],
  'Pension Increase Engine': [
    'Given pension in payment has RPI-linked increases, When annual increase date arrives, Then increase calculated using September RPI index',
    'Given scheme rules specify LPI 0-5% cap and collar, When inflation exceeds 5%, Then pension increase correctly capped with excess handling',
    'Given member has multiple benefit tranches, When annual increase runs, Then each tranche increases separately per applicable rules'
  ],
  'Cashflow Projection Engine': [
    'Given member data cleansed and validated, When cashflow generation runs, Then monthly benefit projections calculated for 70+ years',
    'Given mortality basis is CMI_2022, When survival probabilities applied, Then scheme-specific mortality adjustments incorporated',
    'Given spouse reversionary benefits apply, When calculated, Then contingent spouse pensions modeled using age difference and reversion percentage'
  ],
  'Real-time Quote Integration': [
    'Given liability cashflows generated, When pricing API invoked, Then quote response returns within 60 seconds for 10,000 member scheme',
    'Given gilt yields move during bidding window, When re-quote requested, Then updated price reflects current market conditions',
    'Given quote finalized for trustee review, When documentation requested, Then full methodology and sensitivity analysis delivered'
  ],

  // ========== INVESTMENT RESEARCH AI ==========
  'Earnings Call Summarizer': [
    'Given company earnings call transcript available, When AI summarization runs, Then key themes, sentiment, and guidance extracted with citations',
    'Given management commentary on strategy shifts, When analyzed, Then investment implications highlighted for analyst review',
    'Given multiple earnings calls in same sector, When comparative analysis requested, Then sector-wide themes and outliers identified'
  ],
  'Fundamental Analysis Engine': [
    'Given company financial statements filed, When DCF valuation runs, Then fair value estimate generated with sensitivity tables',
    'Given peer group defined, When multiples comparison generated, Then relative valuation position explained with key drivers',
    'Given model updated with new quarterly data, When re-run, Then changes from previous estimate highlighted with attribution'
  ],
  'Research Note Generator': [
    'Given analyst completes company analysis, When report generated, Then MiFID II compliant research note with disclosures produced',
    'Given target price and rating change, When published, Then previous target and rating history displayed with date of changes',
    'Given research distributed to clients, When access logged, Then consumption tracking enables research budget allocation per unbundling'
  ],
  'Idea Screening Tool': [
    'Given investment criteria defined by analyst, When screening runs, Then qualifying securities ranked by composite score',
    'Given screen results available, When drill-down requested, Then individual security profile shows with screening metric details',
    'Given saved screen updated with new data, When refresh triggered, Then new qualifying and disqualifying securities highlighted'
  ],
  'Sentiment Analysis Engine': [
    'Given news articles and social media ingested, When sentiment scored, Then daily sentiment index calculated per covered security',
    'Given significant sentiment shift detected, When alert triggered, Then analyst notified with source articles and sentiment change magnitude',
    'Given sentiment history accessed, When visualized, Then chart shows sentiment trend overlaid with price movement for correlation'
  ],

  // ========== LONGEVITY MODEL ENHANCEMENT ==========
  'Base Mortality Table Update': [
    'Given CMI publishes new base mortality tables, When data ingested, Then qx rates update with comparison to previous version',
    'Given socio-economic mortality adjustments required, When postcode-linked factors applied, Then member-level mortality expectations reflect deprivation index',
    'Given base table validation runs, When cross-checked against scheme experience, Then credibility-weighted blend produces scheme-specific table'
  ],
  'Improvement Rate Calibration': [
    'Given CMI mortality improvement model updated, When new parameters released, Then platform incorporates updated Core projections within 1 month',
    'Given user selects improvement scenario, When applied, Then percentage reduction per age band and year calculated',
    'Given bespoke improvement overlay required, When configured, Then custom improvement rates merge with base CMI model'
  ],
  'Scheme Experience Analysis': [
    'Given scheme claims data uploaded, When actual vs expected analysis runs, Then A/E ratios calculated by age, sex, and pension amount band',
    'Given low credibility cohort identified, When flagged, Then minimum data requirements for credible analysis communicated',
    'Given material deviation from base table observed, When reported, Then recommended adjustment factors generated with confidence intervals'
  ],
  'Stochastic Longevity Modeling': [
    'Given longevity risk reserve calculation required, When stochastic model runs, Then 99.5th percentile longevity stress quantified',
    'Given 10,000 simulation paths generated, When analysis completes, Then distribution of outcomes displayed with percentile markers',
    'Given specific percentile reserve level selected, When extracted, Then reserve amount calculated with breakdown by cohort'
  ],
  'Life Expectancy Calculator': [
    'Given individual member characteristics entered, When LE calculated, Then expected remaining lifetime displayed with confidence interval',
    'Given cohort of members selected, When aggregate LE calculated, Then weighted average life expectancy with sensitivity to mortality assumptions shown',
    'Given LE comparison required, When run, Then life expectancy vs general population displayed with socioeconomic adjustment factors'
  ],
  'Annuity Reserve Calculator': [
    'Given liability valuation required, When reserving calculation runs, Then present value of annuity cashflows calculated at specified discount rate',
    'Given mortality assumption stress test required, When longevity shock applied, Then impact on reserve expressed in absolute and percentage terms',
    'Given duration and convexity metrics required, When calculated, Then interest rate sensitivity measures displayed for ALM purposes'
  ],
  'Cohort Projection Dashboard': [
    'Given member population selected, When projection dashboard accessed, Then number of survivors, deaths, and payments projected by year',
    'Given alternative mortality assumptions selected, When comparison run, Then side-by-side projection shows impact of assumption changes',
    'Given projection export required, When triggered, Then Excel or PDF report downloads with full cashflow schedule'
  ],

  // ========== OPERATIONAL RESILIENCE FRAMEWORK ==========
  'IBS Dependency Mapping': [
    'Given Important Business Service identified, When dependency mapping runs, Then upstream and downstream dependencies visualized as network graph',
    'Given service owner interviewed, When dependencies documented, Then technology, people, process, and third-party dependencies captured',
    'Given dependency graph complete, When CMDB integration runs, Then linkages to infrastructure components automatically populated'
  ],
  'Impact Tolerance Definition': [
    'Given IBS identified, When impact tolerance workshop conducted, Then maximum tolerable disruption period defined with business justification',
    'Given impact tolerance breached during incident, When escalation triggers, Then executive notification with remediation plan initiated',
    'Given regulatory tolerance requirement changes, When updated, Then affected IBS impact tolerances reviewed within 30 days'
  ],
  'Scenario Library': [
    'Given operational resilience scenarios required, When scenario library accessed, Then 20 core scenarios covering cyber, supplier failure, and infrastructure disruption available',
    'Given custom scenario needed, When configured, Then scenario parameters and expected impacts captured for testing',
    'Given scenario executed, When results recorded, Then evidence and learnings stored for regulatory reporting'
  ],
  'Test Execution Framework': [
    'Given scenario test scheduled, When test orchestration runs, Then simulated disruption introduced with controlled rollback capability',
    'Given test evidence captured, When review completed, Then gaps in resilience capability identified with remediation actions',
    'Given regulatory reporting due, When ICARA extract generated, Then PRA-compliant operational resilience self-assessment produced'
  ],
  'Vendor Dependency Register': [
    'Given third-party vendor provides critical service, When onboarded, Then concentration risk and exit strategy documented',
    'Given vendor risk score calculated, When threshold breached, Then enhanced due diligence workflow triggered',
    'Given vendor incident occurs, When logged, Then impact on IBS assessed and reported to regulators if material'
  ],
  'Concentration Risk Dashboard': [
    'Given third-party dependencies aggregated, When concentration analyzed, Then single points of failure and geographic concentration identified',
    'Given concentration risk mitigation required, When alternative vendor assessed, Then transition plan and cost-benefit documented',
    'Given regulatory inquiry received, When concentration report generated, Then PRA/FCA-ready documentation produced within 5 days'
  ],
  'Recovery Time Objectives': [
    'Given IBS has defined RTO, When tested, Then actual recovery time measured against target with variance documented',
    'Given RTO consistently missed, When escalation triggers, Then improvement plan with investment requirements presented to exec committee',
    'Given technology change affects recovery capability, When assessed, Then updated RTO validated before go-live'
  ],

  // ========== DIGITAL ONBOARDING REDESIGN ==========
  'Identity Verification': [
    'Given customer initiates onboarding, When ID document uploaded, Then OCR extracts details with biometric liveness check in under 60 seconds',
    'Given identity verification fails, When manual review triggered, Then KYC analyst receives case with specific failure reason',
    'Given sanctions and PEP screening required, When check runs, Then match results returned with risk scoring within 30 seconds'
  ],
  'KYC Automation': [
    'Given customer completes digital KYC, When information validated, Then 80%+ of applications proceed without manual intervention',
    'Given adverse media detected, When flagged, Then compliance review workflow initiated with source article links',
    'Given enhanced due diligence required, When triggered, Then additional questions and documentation requests presented to customer'
  ],
  'Document Collection': [
    'Given proof of address required, When document uploaded, Then OCR extracts address with date validation for recency',
    'Given document is unclear or expired, When rejected, Then specific reason communicated with re-upload guidance',
    'Given all required documents collected, When verified, Then document completeness status updates with onboarding progression'
  ],
  'Product Selection': [
    'Given customer eligibility assessed, When products displayed, Then eligible products shown with features and fees clearly presented',
    'Given product complexity requires suitability assessment, When questionnaire completed, Then suitability report generated with recommendation',
    'Given product selected, When added to basket, Then terms and conditions and key information documents presented for acceptance'
  ],
  'Account Creation': [
    'Given customer completes application, When account created, Then welcome email with login credentials sent within 2 minutes',
    'Given account requires approval, When authorized, Then customer notified with next steps for funding',
    'Given cooling-off period applies, When period ends, Then account status updated to active with full functionality enabled'
  ],
  'Funding Flow': [
    'Given customer initiates first deposit, When Open Banking payment selected, Then instant payment confirmation received',
    'Given card payment selected, When 3D Secure completed, Then funds credited to account within 2 hours',
    'Given standing order setup required, When mandate created, Then Direct Debit guarantee and schedule confirmation sent'
  ],
  'Progress Tracker': [
    'Given customer abandons onboarding mid-flow, When reminder sent, Then personalized email with resume link sent within 24 hours',
    'Given customer returns to resume, When session restored, Then progress shown with next step highlighted',
    'Given onboarding complete, When dashboard accessed, Then welcome checklist shows with getting started guidance'
  ],

  // ========== PENSION SCHEME DATA HUB ==========
  'Scheme Configuration Engine': [
    'Given new pension scheme onboarded, When configuration wizard completed, Then scheme rules, benefit structure, and increase rules stored',
    'Given scheme rules amended, When change logged, Then effective date and audit trail maintained with version history',
    'Given scheme merger occurs, When consolidation runs, Then member data migrates with rules mapping to successor scheme'
  ],
  'Member Data Repository': [
    'Given member record accessed, When display requested, Then full benefit entitlement, service history, and correspondence visible',
    'Given member data change received from scheme, When validated, Then record updated with source attribution and timestamp',
    'Given bulk data refresh required, When batch import runs, Then data quality report generated with error counts by field'
  ],
  'Benefit Calculation Service': [
    'Given member requests benefit quote, When calculation runs, Then pension amount calculated per scheme rules with assumption disclosure',
    'Given transfer value requested, When CETV calculated, Then cash equivalent calculated per actuarial factors with 3-month guarantee period',
    'Given retirement options requested, When commutation factor applied, Then lump sum and reduced pension alternatives displayed'
  ],
  'Pensioner Payroll Integration': [
    'Given payroll cycle due, When payment file generated, Then BACS file produced with net payment amounts after tax deductions',
    'Given HMRC PAYE codes received, When applied, Then tax deductions calculated correctly with RTI submission generated',
    'Given payment returned unpaid, When identified, Then tracing process initiated with payment re-routing after address verification'
  ],
  'Dashboard Portal Access': [
    'Given member logs into portal, When dashboard loads, Then benefit summary, documents, and communication history displayed',
    'Given member requests projection, When self-service calculator accessed, Then estimated pension at different retirement dates shown',
    'Given member updates contact details, When change submitted, Then address, email, and phone update across integrated systems'
  ],

  // ========== PRIVATE MARKETS PLATFORM BUILD ==========
  'Fund Data Aggregation': [
    'Given private equity fund reports quarterly, When NAV and performance data ingested, Then fund metrics update with data currency indicator',
    'Given infrastructure fund has multiple underlying assets, When look-through applied, Then asset-level exposures and valuations displayed',
    'Given fund manager provides document, When parsed, Then key data points extracted with audit trail to source document'
  ],
  'Performance Measurement': [
    'Given private markets fund performance measured, When IRR/MOIC calculated, Then returns since inception and by vintage year displayed',
    'Given cashflow data received, When PME analysis runs, Then public market equivalent return comparison generated',
    'Given performance attribution required, When analysis runs, Then value creation decomposed by leverage, growth, and multiple expansion'
  ],
  'Commitment Tracking': [
    'Given capital commitment made to fund, When recorded, Then unfunded commitment tracked with expected drawdown schedule',
    'Given capital call received, When processed, Then commitment balance updated with payment instruction generated',
    'Given distribution received, When recorded, Then DPI and RVPI metrics updated with waterfall analysis'
  ],
  'Portfolio Monitoring': [
    'Given private markets portfolio accessed, When dashboard loads, Then allocation by strategy, geography, and vintage displayed',
    'Given ESG data available for underlying assets, When aggregated, Then portfolio-level ESG scores and PAI metrics calculated',
    'Given liquidity projection required, When modeling runs, Then expected cashflows by quarter for next 5 years displayed'
  ],
  'Manager Due Diligence': [
    'Given fund manager ODD completed, When findings documented, Then operational risk assessment stored with renewal reminder',
    'Given manager incident reported, When logged, Then exposure quantified and escalation workflow triggered',
    'Given DDQ refresh due, When notification sent, Then manager portal access granted for self-certification'
  ],
  'Secondary Market Analysis': [
    'Given secondary sale considered, When market analysis runs, Then expected pricing range based on recent transactions displayed',
    'Given bid received, When evaluated, Then discount/premium to NAV calculated with recommendation',
    'Given secondary sale approved, When transaction closed, Then gain/loss calculated with tax reporting data generated'
  ],
  'Co-Investment Management': [
    'Given co-investment opportunity presented, When evaluated, Then investment committee materials generated with risk assessment',
    'Given co-investment committed, When tracked, Then valuation updates separate from parent fund performance',
    'Given co-investment exit occurs, When proceeds received, Then realized return calculated with attribution to co-invest program'
  ],

  // ========== REGULATORY CHANGE MANAGEMENT ==========
  'Regulatory Horizon Scanning': [
    'Given new regulatory publication released, When scanned, Then relevance assessment generated with affected business areas flagged',
    'Given consultation paper published, When analyzed, Then key proposals summarized with impact assessment questions identified',
    'Given regulatory deadline approaching, When 90 days out, Then escalation notification sent to compliance and business owners'
  ],
  'Impact Assessment Workflow': [
    'Given regulatory change impact assessed, When questionnaire completed, Then impact score calculated with resource estimate',
    'Given high impact regulatory change identified, When escalated, Then steering committee update scheduled within 2 weeks',
    'Given impact assessment signed off, When complete, Then implementation plan with milestones and owners created'
  ],
  'Policy Update Tracker': [
    'Given internal policy requires update, When change drafted, Then version control maintains full edit history with comparison',
    'Given policy update approved, When published, Then affected staff receive notification with attestation requirement',
    'Given policy attestation outstanding, When reminder sent, Then escalation path triggers after 14 days non-compliance'
  ],
  'Implementation Dashboard': [
    'Given regulatory implementation project exists, When dashboard accessed, Then milestones, RAG status, and issues displayed',
    'Given implementation delay identified, When escalated, Then contingency plan and revised timeline presented to project sponsor',
    'Given implementation complete, When signed off, Then regulatory compliance confirmation documented for audit purposes'
  ],
  'Training Management': [
    'Given regulatory change requires staff training, When content created, Then LMS course published with target audience assigned',
    'Given training completion tracked, When threshold met, Then compliance certification updated for affected population',
    'Given training completion rate below target, When 30 days remain, Then manager notification for non-completers sent'
  ],
  'Audit Trail Repository': [
    'Given regulatory audit scheduled, When evidence requested, Then document repository queried with search and filter by regulation',
    'Given audit finding raised, When logged, Then remediation action created with owner and due date',
    'Given audit finding closed, When evidence submitted, Then closure confirmation recorded with supporting documentation'
  ],

  // ========== RISK APPETITE DASHBOARD UPGRADE ==========
  'Risk Metric Aggregation': [
    'Given risk metrics calculated across business units, When aggregated, Then group-level risk profile displayed with drill-down capability',
    'Given risk metric breaches threshold, When alert triggers, Then risk owner and second line notified within 1 hour',
    'Given risk metric trend analyzed, When deterioration detected, Then early warning indicator displays with contributing factors'
  ],
  'Appetite Threshold Configuration': [
    'Given risk appetite thresholds defined by board, When configured, Then green/amber/red bands applied to all relevant metrics',
    'Given appetite reviewed annually, When updated, Then new thresholds effective from specified date with historical comparison available',
    'Given metric approaches amber threshold, When 90% reached, Then watching brief notification sent to risk team'
  ],
  'Board Reporting': [
    'Given quarterly board risk report due, When generated, Then executive summary with key risk indicators and movements produced',
    'Given emerging risk identified, When documented, Then emerging risk register updated with assessment and monitoring plan',
    'Given regulatory risk report required, When PRA stress test data extracted, Then compliant submission format generated'
  ],
  'Stress Testing Dashboard': [
    'Given stress scenario defined, When applied to portfolio, Then capital impact and solvency position under stress displayed',
    'Given reverse stress test required, When run, Then scenarios that would cause failure identified with probability estimates',
    'Given stress test results reviewed, When approved, Then results submitted to regulator within required timeframe'
  ],

  // ========== SAVINGS INVESTMENTS PLATFORM ==========
  'Product Configurator': [
    'Given new ISA product launched, When configured, Then contribution limits, tax wrapper rules, and fund range applied',
    'Given product fee schedule updated, When published, Then platform charges and fund OCF displayed to customers',
    'Given product withdrawn from sale, When configured, Then existing customers can continue but new applications blocked'
  ],
  'Fund Trading Engine': [
    'Given customer places fund trade, When order submitted, Then trade executed at next valuation point with confirmation',
    'Given regular investment scheduled, When payment received, Then automated trade placed with no additional instruction',
    'Given fund switch requested, When processed, Then sell order followed by buy order with no cash drag between'
  ],
  'Tax Wrapper Management': [
    'Given ISA subscription made, When recorded, Then contribution tracked against annual allowance with warning at 90%',
    'Given customer exceeds ISA allowance, When detected, Then excess identified and void ISA rules applied with HMRC notification',
    'Given bed and ISA transaction requested, When processed, Then CGT event crystallized and repurchase within ISA wrapper completed'
  ],
  'Customer Valuation Reports': [
    'Given customer requests portfolio valuation, When generated, Then holdings, cost basis, and current value displayed with performance',
    'Given tax year-end consolidation due, When processed, Then CGT summary and dividend income reports generated',
    'Given platform statement due, When generated, Then annual summary with charges, transactions, and performance sent to customer'
  ],
  'Retirement Income Drawdown': [
    'Given customer in drawdown, When income requested, Then tax-free cash and taxable income calculated per LTA and crystallization',
    'Given UFPLS withdrawal requested, When processed, Then 25% tax-free and 75% taxable portions calculated with RTI submission',
    'Given death benefit claim made, When processed, Then beneficiary options presented based on member age and nomination'
  ],

  // ========== NET ZERO HOUSING TRACKER ==========
  'Property EPC Integration': [
    'Given property EPC rating obtained, When ingested, Then current rating and potential rating displayed with improvement recommendations',
    'Given EPC expiry approaching, When 90 days out, Then renewal reminder sent to property manager',
    'Given portfolio EPC distribution analyzed, When reported, Then percentage of properties below MEES threshold highlighted'
  ],
  'Carbon Footprint Calculator': [
    'Given building energy consumption data ingested, When carbon calculated, Then tCO2e per property and per square meter displayed',
    'Given portfolio carbon footprint aggregated, When compared to target, Then variance from Net Zero pathway shown with remediation options',
    'Given tenant energy consumption estimated, When calculated, Then Scope 3 emissions attributed with data quality disclosure'
  ],
  'Retrofit Planning Tool': [
    'Given property requires energy upgrade, When retrofit assessment runs, Then recommended measures displayed with cost and carbon savings',
    'Given retrofit project approved, When tracked, Then milestones and spend monitored with post-retrofit EPC validation',
    'Given portfolio retrofit program planned, When prioritized, Then properties sequenced by carbon impact per pound invested'
  ],
  'Net Zero Pathway Dashboard': [
    'Given housing portfolio Net Zero target set, When dashboard accessed, Then current carbon position vs glidepath displayed',
    'Given annual progress reviewed, When assessed, Then year-on-year reduction calculated with attribution to retrofit and grid decarbonization',
    'Given CRREM analysis required, When run, Then stranding year and pathway to avoid stranding displayed per property'
  ],

  // ========== INFRASTRUCTURE ASSET MANAGEMENT SYSTEM ==========
  'Asset Lifecycle Management': [
    'Given infrastructure asset acquired, When registered, Then valuation, depreciation schedule, and maintenance plan created',
    'Given asset condition assessment due, When completed, Then condition score updated with remaining useful life estimate',
    'Given asset disposal planned, When executed, Then gain/loss calculated with environmental remediation obligations captured'
  ],
  'Revenue Forecasting': [
    'Given infrastructure asset has contracted revenue, When forecast modeled, Then NPV of future cashflows calculated',
    'Given inflation adjustment applies to revenue, When escalator applied, Then real and nominal revenue projections generated',
    'Given regulatory price review approaches, When scenario modeled, Then allowed revenue under different scenarios compared'
  ],
  'Maintenance Scheduling': [
    'Given preventive maintenance schedule defined, When due date approaches, Then work order generated with contractor notification',
    'Given unplanned maintenance required, When emergency work order created, Then impact on asset availability and budget tracked',
    'Given maintenance history analyzed, When patterns identified, Then predictive maintenance recommendations generated'
  ],
  'Insurance and Compliance': [
    'Given insurance renewal due, When notification sent, Then coverage review completed with risk engineering recommendations',
    'Given regulatory inspection scheduled, When completed, Then findings logged with remediation tracking',
    'Given HSE incident occurs, When reported, Then root cause analysis initiated with RIDDOR compliance checked'
  ],
  'Valuation Engine': [
    'Given infrastructure asset valuation required, When DCF model runs, Then fair value calculated with key assumptions documented',
    'Given comparable transaction data available, When benchmarked, Then valuation multiple comparison provided',
    'Given quarterly valuation update due, When completed, Then NAV impact calculated with movement attribution'
  ]
};

async function applyCompleteCriteria() {
  const files = fs.readdirSync(templatesDir).filter(f => f.endsWith('.json'));
  console.log(`Applying comprehensive story-specific criteria to ${files.length} templates...\n`);

  let totalStoriesUpdated = 0;
  let storiesWithBespokeCriteria = 0;

  for (const file of files) {
    const filePath = path.join(templatesDir, file);
    const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    
    let fileStoriesUpdated = 0;
    let fileBespokeCriteria = 0;
    
    if (content.features) {
      content.features = content.features.map((feature: any) => {
        if (feature.stories) {
          feature.stories = feature.stories.map((story: any) => {
            const storyName = story.name;
            
            if (allStoryCriteria[storyName]) {
              fileBespokeCriteria++;
              storiesWithBespokeCriteria++;
              story.acceptanceCriteria = allStoryCriteria[storyName];
            } else {
              story.acceptanceCriteria = generateDomainCriteria(storyName, content.bu, content.division);
            }
            
            fileStoriesUpdated++;
            totalStoriesUpdated++;
            return story;
          });
        }
        return feature;
      });
    }
    
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
    const percentage = fileStoriesUpdated > 0 ? Math.round((fileBespokeCriteria / fileStoriesUpdated) * 100) : 0;
    console.log(`✓ ${file}: ${fileBespokeCriteria}/${fileStoriesUpdated} bespoke (${percentage}%)`);
  }

  const overallPercentage = Math.round((storiesWithBespokeCriteria / totalStoriesUpdated) * 100);
  console.log(`\n=== Summary ===`);
  console.log(`Total stories: ${totalStoriesUpdated}`);
  console.log(`Bespoke criteria: ${storiesWithBespokeCriteria} (${overallPercentage}%)`);
  console.log(`Contextual criteria: ${totalStoriesUpdated - storiesWithBespokeCriteria}`);
}

function generateDomainCriteria(storyName: string, bu: string, division: string): string[] {
  const domain = (division + ' ' + bu).toLowerCase();
  const nameLower = storyName.toLowerCase();
  
  if (domain.includes('retirement') || domain.includes('pension') || domain.includes('lgr')) {
    if (nameLower.includes('calculation') || nameLower.includes('benefit') || nameLower.includes('projection')) {
      return [
        `Given ${storyName} is initiated for pension scheme, When actuarial assumptions applied, Then results comply with TPR and FCA regulatory standards`,
        `Given calculation parameters are set, When processing completes, Then member-level outputs are validated against expected ranges with variance reporting`,
        `Given scheme-specific rules apply, When overrides configured, Then custom calculation logic reflects scheme deed amendments`
      ];
    }
    if (nameLower.includes('data') || nameLower.includes('member') || nameLower.includes('scheme')) {
      return [
        `Given ${storyName} receives pension scheme data, When validation runs, Then records comply with Pensions Dashboard Programme data standards`,
        `Given data quality issues identified, When cleansing workflow triggered, Then corrections are tracked with full audit trail for TPR compliance`,
        `Given GDPR SAR request received, When member data extracted, Then complete records provided within statutory 30-day deadline`
      ];
    }
  }
  
  if (domain.includes('lgim') || domain.includes('investment')) {
    if (nameLower.includes('esg') || nameLower.includes('climate') || nameLower.includes('carbon') || nameLower.includes('scenario') || nameLower.includes('temperature')) {
      return [
        `Given ${storyName} processes ESG data, When SFDR reporting triggered, Then Article 8/9 fund disclosures meet regulatory requirements`,
        `Given climate metrics calculated, When TCFD alignment assessed, Then portfolio temperature alignment score is generated`,
        `Given ESG data gaps exist, When estimation applied, Then methodology disclosure meets FCA sustainability labelling requirements`
      ];
    }
    if (nameLower.includes('portfolio') || nameLower.includes('fund') || nameLower.includes('mandate') || nameLower.includes('analysis') || nameLower.includes('research')) {
      return [
        `Given ${storyName} for client mandate, When performance calculated, Then GIPS-compliant returns are generated with benchmark comparison`,
        `Given client reporting period ends, When factsheet generated, Then MiFID II cost disclosures and ESG metrics are included`,
        `Given portfolio rebalancing triggered, When trades executed, Then best execution documentation is maintained per FCA requirements`
      ];
    }
  }
  
  if (domain.includes('housing') || domain.includes('property') || domain.includes('btr') || domain.includes('infrastructure')) {
    if (nameLower.includes('tenant') || nameLower.includes('rent') || nameLower.includes('lettings') || nameLower.includes('property')) {
      return [
        `Given ${storyName} for BTR property, When tenancy created, Then AST complies with Housing Act 2004 and Renters Reform requirements`,
        `Given rent collection processed, When arrears detected, Then pre-action protocol compliant process initiates within regulatory timeframes`,
        `Given tenant raises complaint, When logged, Then response provided within 14 days per Redress Scheme requirements`
      ];
    }
    if (nameLower.includes('maintenance') || nameLower.includes('repair') || nameLower.includes('asset') || nameLower.includes('retrofit') || nameLower.includes('epc')) {
      return [
        `Given ${storyName} for property portfolio, When maintenance required, Then response SLA meets HHSRS Category 1 hazard requirements`,
        `Given gas safety check due, When scheduled, Then CP12 certificate obtained before annual expiry with tenant notification`,
        `Given EPC rating below target, When retrofit assessed, Then upgrade pathway aligns with MEES 2028 compliance requirements`
      ];
    }
  }
  
  if (domain.includes('insurance') || domain.includes('protection')) {
    if (nameLower.includes('underwriting') || nameLower.includes('risk') || nameLower.includes('quote') || nameLower.includes('product')) {
      return [
        `Given ${storyName} for protection application, When risk assessed, Then underwriting decision aligns with treating customers fairly (TCF) principles`,
        `Given medical disclosure made, When evidence reviewed, Then decision timeline meets FCA DISP complaint handling requirements`,
        `Given premium calculated, When disclosed to customer, Then Consumer Duty fair value assessment is documented`
      ];
    }
    if (nameLower.includes('claim') || nameLower.includes('settlement') || nameLower.includes('payment')) {
      return [
        `Given ${storyName} for protection claim, When assessed, Then decision made within published claim handling SLA`,
        `Given claim declined, When communicated, Then clear explanation and complaints process information provided per FCA requirements`,
        `Given settlement approved, When paid, Then funds reach beneficiary within 3 business days of approval`
      ];
    }
  }
  
  if (domain.includes('group') || domain.includes('function') || domain.includes('enterprise')) {
    if (nameLower.includes('resilience') || nameLower.includes('recovery') || nameLower.includes('scenario') || nameLower.includes('dependency')) {
      return [
        `Given ${storyName} for operational resilience, When IBS assessed, Then impact tolerance within PRA/FCA requirements`,
        `Given scenario test executed, When results recorded, Then evidence captured for regulatory self-assessment`,
        `Given third party dependency identified, When risk scored, Then concentration and substitutability documented`
      ];
    }
    if (nameLower.includes('regulatory') || nameLower.includes('compliance') || nameLower.includes('audit') || nameLower.includes('policy')) {
      return [
        `Given ${storyName} regulatory requirement identified, When assessed, Then impact score and implementation plan created`,
        `Given policy update required, When drafted, Then version control and approval workflow maintained`,
        `Given audit finding raised, When documented, Then remediation tracked with owner and due date`
      ];
    }
  }
  
  return [
    `Given ${storyName} is executed, When all validations pass, Then processing completes within defined SLA with full audit trail`,
    `Given business rules apply, When evaluated, Then outcomes align with regulatory requirements and internal policies`,
    `Given exception occurs, When handled, Then appropriate escalation and notification processes are triggered`
  ];
}

applyCompleteCriteria().catch(console.error);
