/**
 * PALANTIR APPROVAL SERVICE
 *
 * Source of Truth: PALANTIR FOUNDRY
 *
 * Manages approval workflows through Palantir:
 * - Extraction review items
 * - Dashboard approvals
 * - Rule-triggered approvals
 *
 * Uses Intervention objects to store approval requests
 * with category="approval" and status tracking.
 */

import { getPalantirService } from '../mcp/MCPServiceFactory.js';
import { getPalantirLLMBridge } from './PalantirLLMBridge.js';
import { db } from '../db.js';
import { extractionReviewQueue, dashboardTemplates, approvalRequests } from '../db/schema.js';
import { eq, and } from 'drizzle-orm';
import { PALANTIR_OBJECT_TYPES, PALANTIR_ACTIONS } from '../constants/palantirOntology.js';

export interface ApprovalItem {
  id: string;
  type: 'extraction' | 'dashboard' | 'rule_enforcement';
  entityType?: string;
  entityId?: string;
  title: string;
  description: string;
  status: 'pending' | 'approved' | 'rejected';
  sourceAgent?: string;
  requestedBy?: string;
  requestedAt: Date;
  approvedBy?: string;
  approvedAt?: Date;
  metadata?: Record<string, any>;
}

export interface ApprovalStats {
  total: number;
  pending: number;
  approved: number;
  rejected: number;
  bySource: Record<string, number>;
  byType: Record<string, number>;
}

class PalantirApprovalService {
  private palantirService = getPalantirService();

  /**
   * Check if Palantir is available for approval operations
   */
  isPalantirAvailable(): boolean {
    return !!this.palantirService;
  }

  /**
   * Get all pending extraction items
   * First tries Palantir, falls back to PostgreSQL
   */
  async getExtractionItems(): Promise<ApprovalItem[]> {
    try {
      if (this.palantirService) {
        // Query AtlasInsight objects with category=approval, type=extraction
        const result = await this.palantirService.listObjects(PALANTIR_OBJECT_TYPES.INTERVENTION, { pageSize: 100 });
        const approvals = (result.data || []).filter((item: any) =>
          item.category === 'approval' &&
          item.insight_type === 'extraction' &&
          item.status === 'pending'
        );

        return approvals.map((item: any) => ({
          id: item.insight_id || item.id,
          type: 'extraction' as const,
          entityType: item.entity_type,
          entityId: item.entity_id,
          title: item.title || item.description?.substring(0, 50) || 'Extraction Item',
          description: item.description || '',
          status: this.mapStatus(item.status),
          sourceAgent: 'policy-as-code-extractor',
          requestedBy: item.created_by,
          requestedAt: new Date(item.created_at || Date.now()),
          metadata: item.metadata,
        }));
      }
    } catch (error: any) {
      console.warn('[PalantirApproval] Palantir getExtractionItems failed:', error.message);
    }

    // Fallback to PostgreSQL
    const items = await db
      .select()
      .from(extractionReviewQueue)
      .where(eq(extractionReviewQueue.reviewStatus, 'pending'));

    return items.map(item => {
      const itemData = item.itemData as Record<string, any> || {};
      return {
        id: item.id,
        type: 'extraction' as const,
        entityType: item.itemType,
        entityId: item.id,
        title: itemData.title || `${item.itemType} Item`,
        description: itemData.description || '',
        status: this.mapStatus(item.reviewStatus || 'pending'),
        sourceAgent: 'policy-as-code-extractor',
        requestedAt: item.createdAt || new Date(),
        metadata: itemData,
      };
    });
  }

  /**
   * Get all pending dashboard items
   */
  async getDashboardItems(): Promise<ApprovalItem[]> {
    try {
      if (this.palantirService) {
        const result = await this.palantirService.listObjects(PALANTIR_OBJECT_TYPES.INTERVENTION, { pageSize: 100 });
        const dashboards = (result.data || []).filter((item: any) =>
          item.category === 'approval' &&
          item.insight_type === 'dashboard' &&
          item.status === 'pending'
        );

        return dashboards.map((item: any) => ({
          id: item.insight_id || item.id,
          type: 'dashboard' as const,
          title: item.title || 'Auto-generated Dashboard',
          description: item.description || '',
          status: this.mapStatus(item.status),
          sourceAgent: 'dashboard-generator',
          requestedBy: item.created_by,
          requestedAt: new Date(item.created_at || Date.now()),
          metadata: item.metadata,
        }));
      }
    } catch (error: any) {
      console.warn('[PalantirApproval] Palantir getDashboardItems failed:', error.message);
    }

    // Fallback to PostgreSQL
    const items = await db
      .select()
      .from(dashboardTemplates)
      .where(
        and(
          eq(dashboardTemplates.autoGenerated, true),
          eq(dashboardTemplates.isActive, false)
        )
      );

    return items.map(item => ({
      id: item.id,
      type: 'dashboard' as const,
      title: item.templateName || 'Auto-generated Dashboard',
      description: item.description || '',
      status: 'pending' as const,
      sourceAgent: 'dashboard-generator',
      requestedAt: item.createdAt || new Date(),
      metadata: { layoutConfig: item.layoutConfig },
    }));
  }

  /**
   * Get all rule-triggered approval requests
   */
  async getRuleApprovals(): Promise<ApprovalItem[]> {
    try {
      if (this.palantirService) {
        const result = await this.palantirService.listObjects(PALANTIR_OBJECT_TYPES.INTERVENTION, { pageSize: 100 });
        const approvals = (result.data || []).filter((item: any) =>
          item.category === 'approval' &&
          item.insight_type === 'rule_enforcement' &&
          item.status === 'pending'
        );

        return approvals.map((item: any) => ({
          id: item.insight_id || item.id,
          type: 'rule_enforcement' as const,
          entityType: item.entity_type,
          entityId: item.entity_id,
          title: item.title || 'Rule Approval Required',
          description: item.description || '',
          status: this.mapStatus(item.status),
          sourceAgent: 'governance-rules',
          requestedBy: item.created_by,
          requestedAt: new Date(item.created_at || Date.now()),
          metadata: item.metadata,
        }));
      }
    } catch (error: any) {
      console.warn('[PalantirApproval] Palantir getRuleApprovals failed:', error.message);
    }

    // Fallback to PostgreSQL
    const items = await db
      .select()
      .from(approvalRequests)
      .where(eq(approvalRequests.status, 'pending'));

    return items.map(item => ({
      id: item.id,
      type: 'rule_enforcement' as const,
      entityType: item.entityType || undefined,
      entityId: item.entityId || undefined,
      title: `${item.requestType}: ${item.entityType}`,
      description: item.reason || '',
      status: this.mapStatus(item.status),
      sourceAgent: 'governance-rules',
      requestedBy: item.requestedBy || undefined,
      requestedAt: item.requestedAt || new Date(),
      approvedBy: item.approvedBy || undefined,
      approvedAt: item.approvedAt || undefined,
      metadata: item.metadata as Record<string, any>,
    }));
  }

  /**
   * Get all approval items combined
   */
  async getAllItems(): Promise<ApprovalItem[]> {
    const [extraction, dashboards, rules] = await Promise.all([
      this.getExtractionItems(),
      this.getDashboardItems(),
      this.getRuleApprovals(),
    ]);

    return [...extraction, ...dashboards, ...rules].sort(
      (a, b) => b.requestedAt.getTime() - a.requestedAt.getTime()
    );
  }

  /**
   * Approve an item
   */
  async approve(itemId: string, type: string, approverId: string): Promise<{ success: boolean; message: string }> {
    try {
      if (this.palantirService) {
        // Update in Palantir using atlas-create-insight action to update status
        await this.palantirService.applyAction(PALANTIR_ACTIONS.CREATE_INTERVENTION, {
          insight_id: itemId,
          title: 'Approval Status Update',
          description: `Item ${itemId} approved by ${approverId}`,
          category: 'approval',
          insight_type: type,
          status: 'approved',
          severity: 'info',
          created_by: approverId,
          approved_at: new Date().toISOString(),
        });
      }

      // Also update PostgreSQL for consistency during migration
      if (type === 'extraction') {
        // Use raw SQL for update since schema types don't match
        try {
          await db.execute(`UPDATE extraction_review_queue SET review_status = 'approved', reviewed_by = '${approverId}', reviewed_at = NOW() WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not update extraction queue:', e);
        }
      } else if (type === 'dashboard') {
        try {
          await db.execute(`UPDATE dashboard_templates SET is_active = true, updated_at = NOW() WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not update dashboard template:', e);
        }
      } else if (type === 'rule_enforcement') {
        try {
          await db.execute(`UPDATE approval_requests SET status = 'approved', approved_by = '${approverId}', approved_at = NOW() WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not update approval request:', e);
        }
      }

      return { success: true, message: `Item ${itemId} approved successfully` };
    } catch (error: any) {
      console.error('[PalantirApproval] Approve failed:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Reject an item
   */
  async reject(itemId: string, type: string, rejecterId: string, reason?: string): Promise<{ success: boolean; message: string }> {
    try {
      if (this.palantirService) {
        await this.palantirService.applyAction(PALANTIR_ACTIONS.CREATE_INTERVENTION, {
          insight_id: itemId,
          title: 'Rejection Status Update',
          description: reason || `Item ${itemId} rejected by ${rejecterId}`,
          category: 'approval',
          insight_type: type,
          status: 'rejected',
          severity: 'warning',
          created_by: rejecterId,
          rejected_at: new Date().toISOString(),
        });
      }

      // Update PostgreSQL
      if (type === 'extraction') {
        try {
          await db.execute(`UPDATE extraction_review_queue SET review_status = 'rejected', reviewed_by = '${rejecterId}', reviewed_at = NOW() WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not update extraction queue:', e);
        }
      } else if (type === 'dashboard') {
        try {
          await db.execute(`DELETE FROM dashboard_templates WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not delete dashboard template:', e);
        }
      } else if (type === 'rule_enforcement') {
        try {
          const escapedReason = (reason || '').replace(/'/g, "''");
          await db.execute(`UPDATE approval_requests SET status = 'rejected', approved_by = '${rejecterId}', approved_at = NOW(), approver_comments = '${escapedReason}' WHERE id = '${itemId}'`);
        } catch (e) {
          console.warn('[PalantirApproval] Could not update approval request:', e);
        }
      }

      return { success: true, message: `Item ${itemId} rejected successfully` };
    } catch (error: any) {
      console.error('[PalantirApproval] Reject failed:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Get approval statistics
   */
  async getStats(): Promise<ApprovalStats> {
    const allItems = await this.getAllItems();

    const stats: ApprovalStats = {
      total: allItems.length,
      pending: allItems.filter(i => i.status === 'pending').length,
      approved: allItems.filter(i => i.status === 'approved').length,
      rejected: allItems.filter(i => i.status === 'rejected').length,
      bySource: {},
      byType: {},
    };

    // Group by source
    for (const item of allItems) {
      const source = item.sourceAgent || 'unknown';
      stats.bySource[source] = (stats.bySource[source] || 0) + 1;
    }

    // Group by type
    for (const item of allItems) {
      stats.byType[item.type] = (stats.byType[item.type] || 0) + 1;
    }

    return stats;
  }

  /**
   * Create a new approval request
   */
  async createApprovalRequest(request: {
    type: 'extraction' | 'dashboard' | 'rule_enforcement';
    entityType?: string;
    entityId?: string;
    title: string;
    description: string;
    requestedBy?: string;
    metadata?: Record<string, any>;
  }): Promise<{ id: string; success: boolean }> {
    const id = `approval-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    try {
      if (this.palantirService) {
        await this.palantirService.applyAction(PALANTIR_ACTIONS.CREATE_INTERVENTION, {
          insight_id: id,
          title: request.title,
          description: request.description,
          category: 'approval',
          insight_type: request.type,
          status: 'pending',
          severity: 'info',
          created_by: request.requestedBy || 'system',
          entity_type: request.entityType,
          entity_id: request.entityId,
          metadata: request.metadata ? JSON.stringify(request.metadata) : undefined,
        });
      }

      return { id, success: true };
    } catch (error: any) {
      console.error('[PalantirApproval] Create approval request failed:', error);
      return { id: '', success: false };
    }
  }

  // Helper methods
  private mapStatus(status: string | null | undefined): 'pending' | 'approved' | 'rejected' {
    if (!status) return 'pending';
    const s = status.toLowerCase();
    if (s === 'approved' || s === 'complete' || s === 'done') return 'approved';
    if (s === 'rejected' || s === 'denied' || s === 'cancelled') return 'rejected';
    return 'pending';
  }
}

// Singleton
let _approvalService: PalantirApprovalService | null = null;

export function getPalantirApprovalService(): PalantirApprovalService {
  if (!_approvalService) {
    _approvalService = new PalantirApprovalService();
  }
  return _approvalService;
}
