/**
 * SEED AGENT ATTRIBUTES
 *
 * Seeds the agent_attributes table with dynamic attributes for all agents.
 * Each attribute can power a dashboard widget, enabling "liquid" UI.
 *
 * Idempotent - safe to run multiple times (uses upsert pattern)
 */

import { db } from '../db.js';
import { sql } from 'drizzle-orm';

interface AttributeDefinition {
  name: string;
  displayName: string;
  description: string;
  category: string;
  dataType: 'number' | 'percentage' | 'currency' | 'text' | 'date' | 'boolean' | 'array' | 'status';
  unit?: string;
  format?: string;
  valueSource: 'calculated' | 'aggregated' | 'static' | 'api' | 'rulebricks';
  calculationRule?: string;
  aggregationMethod?: string;
  defaultWidgetType: 'stat-card' | 'gauge' | 'chart-line' | 'chart-bar' | 'chart-pie' | 'table' | 'list' | 'progress' | 'status-badge' | 'heat-map' | 'kpi-card' | 'trend-card';
  thresholds?: { warning: number; critical: number };
  palantirPropertyName?: string;
  refreshInterval?: number;
}

// ============================================================================
// FINOPS AGENT ATTRIBUTES
// ============================================================================
const FINOPS_ATTRIBUTES: AttributeDefinition[] = [
  // Budget Metrics
  {
    name: 'total_budget',
    displayName: 'Total Budget',
    description: 'Total budget allocated across all projects',
    category: 'budget',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'budgetTotal',
  },
  {
    name: 'budget_spent',
    displayName: 'Budget Spent',
    description: 'Total budget spent to date',
    category: 'budget',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'budgetSpent',
  },
  {
    name: 'budget_remaining',
    displayName: 'Budget Remaining',
    description: 'Remaining budget across all projects',
    category: 'budget',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    calculationRule: 'total_budget - budget_spent',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'budgetRemaining',
  },
  {
    name: 'budget_variance',
    displayName: 'Budget Variance',
    description: 'Percentage variance from planned budget',
    category: 'budget',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: '((budget_spent - planned_spend) / planned_spend) * 100',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 10, critical: 20 },
    palantirPropertyName: 'budgetVariance',
  },
  {
    name: 'burn_rate',
    displayName: 'Monthly Burn Rate',
    description: 'Average monthly expenditure rate',
    category: 'budget',
    dataType: 'currency',
    unit: 'USD/month',
    valueSource: 'calculated',
    calculationRule: 'budget_spent / months_elapsed',
    defaultWidgetType: 'trend-card',
    palantirPropertyName: 'burnRate',
  },
  {
    name: 'runway_months',
    displayName: 'Budget Runway',
    description: 'Months of budget remaining at current burn rate',
    category: 'budget',
    dataType: 'number',
    unit: 'months',
    valueSource: 'calculated',
    calculationRule: 'budget_remaining / burn_rate',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 1 },
    palantirPropertyName: 'budgetRunway',
  },

  // EVM Metrics
  {
    name: 'cpi',
    displayName: 'Cost Performance Index',
    description: 'Earned value / actual cost - measures cost efficiency',
    category: 'evm',
    dataType: 'number',
    valueSource: 'calculated',
    calculationRule: 'earned_value / actual_cost',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 0.95, critical: 0.9 },
    palantirPropertyName: 'cpi',
  },
  {
    name: 'spi',
    displayName: 'Schedule Performance Index',
    description: 'Earned value / planned value - measures schedule efficiency',
    category: 'evm',
    dataType: 'number',
    valueSource: 'calculated',
    calculationRule: 'earned_value / planned_value',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 0.95, critical: 0.9 },
    palantirPropertyName: 'spi',
  },
  {
    name: 'earned_value',
    displayName: 'Earned Value',
    description: 'Budgeted cost of work performed',
    category: 'evm',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'earnedValue',
  },
  {
    name: 'planned_value',
    displayName: 'Planned Value',
    description: 'Budgeted cost of work scheduled',
    category: 'evm',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'plannedValue',
  },
  {
    name: 'actual_cost',
    displayName: 'Actual Cost',
    description: 'Actual cost of work performed',
    category: 'evm',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'actualCost',
  },
  {
    name: 'estimate_at_completion',
    displayName: 'Estimate at Completion',
    description: 'Projected total cost at project completion',
    category: 'evm',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    calculationRule: 'actual_cost + (total_budget - earned_value) / cpi',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'eac',
  },
  {
    name: 'variance_at_completion',
    displayName: 'Variance at Completion',
    description: 'Projected budget variance at project completion',
    category: 'evm',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    calculationRule: 'total_budget - estimate_at_completion',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'vac',
  },

  // Cost Analysis
  {
    name: 'projects_over_budget',
    displayName: 'Projects Over Budget',
    description: 'Number of projects exceeding budget',
    category: 'analysis',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'projectsOverBudget',
  },
  {
    name: 'cost_efficiency_score',
    displayName: 'Cost Efficiency Score',
    description: 'Overall portfolio cost efficiency rating',
    category: 'analysis',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'cost_efficiency_rule',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'costEfficiencyScore',
  },
  {
    name: 'budget_trend',
    displayName: 'Budget Trend',
    description: 'Historical budget utilization trend',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-line',
    palantirPropertyName: 'budgetTrend',
  },
  {
    name: 'cost_by_category',
    displayName: 'Cost by Category',
    description: 'Budget distribution by category',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-pie',
    palantirPropertyName: 'costByCategory',
  },
];

// ============================================================================
// TMO AGENT ATTRIBUTES
// ============================================================================
const TMO_ATTRIBUTES: AttributeDefinition[] = [
  // Schedule Metrics
  {
    name: 'total_projects',
    displayName: 'Total Projects',
    description: 'Total number of active projects',
    category: 'portfolio',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalProjects',
  },
  {
    name: 'projects_on_track',
    displayName: 'Projects On Track',
    description: 'Number of projects on schedule',
    category: 'portfolio',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'projectsOnTrack',
  },
  {
    name: 'projects_at_risk',
    displayName: 'Projects At Risk',
    description: 'Number of projects with schedule risk',
    category: 'portfolio',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'projectsAtRisk',
  },
  {
    name: 'projects_delayed',
    displayName: 'Projects Delayed',
    description: 'Number of projects behind schedule',
    category: 'portfolio',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 4 },
    palantirPropertyName: 'projectsDelayed',
  },
  {
    name: 'schedule_health_score',
    displayName: 'Schedule Health Score',
    description: 'Overall portfolio schedule health',
    category: 'portfolio',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'schedule_health_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 75, critical: 50 },
    palantirPropertyName: 'scheduleHealthScore',
  },

  // Milestone Metrics
  {
    name: 'total_milestones',
    displayName: 'Total Milestones',
    description: 'Total milestones across all projects',
    category: 'milestones',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalMilestones',
  },
  {
    name: 'milestones_completed',
    displayName: 'Milestones Completed',
    description: 'Number of completed milestones',
    category: 'milestones',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'milestonesCompleted',
  },
  {
    name: 'milestones_upcoming',
    displayName: 'Upcoming Milestones',
    description: 'Milestones due in next 30 days',
    category: 'milestones',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'milestonesUpcoming',
  },
  {
    name: 'milestones_overdue',
    displayName: 'Overdue Milestones',
    description: 'Number of overdue milestones',
    category: 'milestones',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'milestonesOverdue',
  },
  {
    name: 'milestone_completion_rate',
    displayName: 'Milestone Completion Rate',
    description: 'Percentage of milestones completed on time',
    category: 'milestones',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: '(milestones_completed_on_time / total_milestones_due) * 100',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 80, critical: 60 },
    palantirPropertyName: 'milestoneCompletionRate',
  },

  // Timeline Metrics
  {
    name: 'average_project_duration',
    displayName: 'Average Project Duration',
    description: 'Average duration of projects in months',
    category: 'timeline',
    dataType: 'number',
    unit: 'months',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'avgProjectDuration',
  },
  {
    name: 'average_delay_days',
    displayName: 'Average Delay',
    description: 'Average days behind schedule for delayed projects',
    category: 'timeline',
    dataType: 'number',
    unit: 'days',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'avgDelayDays',
  },
  {
    name: 'critical_path_items',
    displayName: 'Critical Path Items',
    description: 'Number of items on critical path',
    category: 'timeline',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'criticalPathItems',
  },
  {
    name: 'dependency_blockers',
    displayName: 'Dependency Blockers',
    description: 'Number of blocking dependencies',
    category: 'timeline',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'dependencyBlockers',
  },
  {
    name: 'velocity',
    displayName: 'Team Velocity',
    description: 'Average story points completed per sprint',
    category: 'timeline',
    dataType: 'number',
    unit: 'points/sprint',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'trend-card',
    palantirPropertyName: 'velocity',
  },
  {
    name: 'timeline_forecast',
    displayName: 'Timeline Forecast',
    description: 'Forecasted completion dates by project',
    category: 'timeline',
    dataType: 'array',
    valueSource: 'calculated',
    defaultWidgetType: 'chart-bar',
    palantirPropertyName: 'timelineForecast',
  },
];

// ============================================================================
// RISK AGENT ATTRIBUTES
// ============================================================================
const RISK_ATTRIBUTES: AttributeDefinition[] = [
  // Risk Counts
  {
    name: 'total_risks',
    displayName: 'Total Risks',
    description: 'Total identified risks across portfolio',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalRisks',
  },
  {
    name: 'critical_risks',
    displayName: 'Critical Risks',
    description: 'Number of critical severity risks',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'criticalRisks',
  },
  {
    name: 'high_risks',
    displayName: 'High Risks',
    description: 'Number of high severity risks',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 5, critical: 10 },
    palantirPropertyName: 'highRisks',
  },
  {
    name: 'medium_risks',
    displayName: 'Medium Risks',
    description: 'Number of medium severity risks',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'mediumRisks',
  },
  {
    name: 'low_risks',
    displayName: 'Low Risks',
    description: 'Number of low severity risks',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'lowRisks',
  },

  // Risk Scores
  {
    name: 'portfolio_risk_score',
    displayName: 'Portfolio Risk Score',
    description: 'Overall portfolio risk assessment score',
    category: 'scores',
    dataType: 'number',
    valueSource: 'rulebricks',
    calculationRule: 'portfolio_risk_score_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 60, critical: 80 },
    palantirPropertyName: 'portfolioRiskScore',
  },
  {
    name: 'risk_exposure',
    displayName: 'Risk Exposure',
    description: 'Total financial exposure from identified risks',
    category: 'scores',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'riskExposure',
  },
  {
    name: 'mitigated_exposure',
    displayName: 'Mitigated Exposure',
    description: 'Risk exposure reduced through mitigation',
    category: 'scores',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'mitigatedExposure',
  },
  {
    name: 'residual_risk',
    displayName: 'Residual Risk',
    description: 'Remaining risk after mitigation',
    category: 'scores',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    calculationRule: 'risk_exposure - mitigated_exposure',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'residualRisk',
  },

  // Risk Management
  {
    name: 'risks_mitigated',
    displayName: 'Risks Mitigated',
    description: 'Number of risks with active mitigation',
    category: 'management',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'risksMitigated',
  },
  {
    name: 'risks_accepted',
    displayName: 'Risks Accepted',
    description: 'Number of risks formally accepted',
    category: 'management',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'risksAccepted',
  },
  {
    name: 'risks_pending_review',
    displayName: 'Pending Review',
    description: 'Risks awaiting review or approval',
    category: 'management',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 5, critical: 10 },
    palantirPropertyName: 'risksPendingReview',
  },
  {
    name: 'overdue_mitigations',
    displayName: 'Overdue Mitigations',
    description: 'Mitigation actions past due date',
    category: 'management',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'overdueMitigations',
  },

  // Risk Distribution
  {
    name: 'risks_by_category',
    displayName: 'Risks by Category',
    description: 'Risk distribution across categories',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-pie',
    palantirPropertyName: 'risksByCategory',
  },
  {
    name: 'risk_heat_map',
    displayName: 'Risk Heat Map',
    description: 'Risk matrix showing probability vs impact',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'heat-map',
    palantirPropertyName: 'riskHeatMap',
  },
  {
    name: 'risk_trend',
    displayName: 'Risk Trend',
    description: 'Historical risk count trend',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-line',
    palantirPropertyName: 'riskTrend',
  },
];

// ============================================================================
// PMO AGENT ATTRIBUTES
// ============================================================================
const PMO_ATTRIBUTES: AttributeDefinition[] = [
  // Portfolio Health
  {
    name: 'portfolio_health_score',
    displayName: 'Portfolio Health Score',
    description: 'Overall health of the project portfolio',
    category: 'health',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'portfolio_health_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 70, critical: 50 },
    palantirPropertyName: 'portfolioHealthScore',
  },
  {
    name: 'projects_green',
    displayName: 'Green Projects',
    description: 'Projects with green health status',
    category: 'health',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'projectsGreen',
  },
  {
    name: 'projects_amber',
    displayName: 'Amber Projects',
    description: 'Projects with amber health status',
    category: 'health',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'projectsAmber',
  },
  {
    name: 'projects_red',
    displayName: 'Red Projects',
    description: 'Projects with red health status',
    category: 'health',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 4 },
    palantirPropertyName: 'projectsRed',
  },

  // Governance
  {
    name: 'governance_compliance',
    displayName: 'Governance Compliance',
    description: 'Percentage of projects meeting governance requirements',
    category: 'governance',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 85, critical: 70 },
    palantirPropertyName: 'governanceCompliance',
  },
  {
    name: 'pending_approvals',
    displayName: 'Pending Approvals',
    description: 'Number of items awaiting governance approval',
    category: 'governance',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 5, critical: 10 },
    palantirPropertyName: 'pendingApprovals',
  },
  {
    name: 'stage_gate_success_rate',
    displayName: 'Stage Gate Success Rate',
    description: 'Percentage of stage gates passed on first attempt',
    category: 'governance',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'stageGateSuccessRate',
  },

  // Resource
  {
    name: 'total_resources',
    displayName: 'Total Resources',
    description: 'Total number of resources across projects',
    category: 'resources',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalResources',
  },
  {
    name: 'resource_utilization',
    displayName: 'Resource Utilization',
    description: 'Average resource utilization percentage',
    category: 'resources',
    dataType: 'percentage',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 85, critical: 95 },
    palantirPropertyName: 'resourceUtilization',
  },
  {
    name: 'overallocated_resources',
    displayName: 'Overallocated Resources',
    description: 'Resources allocated above 100%',
    category: 'resources',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'overallocatedResources',
  },

  // Status
  {
    name: 'status_reports_due',
    displayName: 'Reports Due',
    description: 'Status reports due this week',
    category: 'reporting',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'statusReportsDue',
  },
  {
    name: 'overdue_reports',
    displayName: 'Overdue Reports',
    description: 'Status reports past due date',
    category: 'reporting',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'overdueReports',
  },
  {
    name: 'portfolio_by_stage',
    displayName: 'Portfolio by Stage',
    description: 'Distribution of projects by SAFe stage',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-bar',
    palantirPropertyName: 'portfolioByStage',
  },
];

// ============================================================================
// GOVERNANCE AGENT ATTRIBUTES
// ============================================================================
const GOVERNANCE_ATTRIBUTES: AttributeDefinition[] = [
  // Compliance
  {
    name: 'compliance_score',
    displayName: 'Compliance Score',
    description: 'Overall compliance rating',
    category: 'compliance',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'compliance_score_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 85, critical: 70 },
    palantirPropertyName: 'complianceScore',
  },
  {
    name: 'policy_violations',
    displayName: 'Policy Violations',
    description: 'Number of active policy violations',
    category: 'compliance',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'policyViolations',
  },
  {
    name: 'compliant_projects',
    displayName: 'Compliant Projects',
    description: 'Projects meeting all compliance requirements',
    category: 'compliance',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'compliantProjects',
  },
  {
    name: 'audit_findings',
    displayName: 'Open Audit Findings',
    description: 'Number of open audit findings',
    category: 'compliance',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 5, critical: 10 },
    palantirPropertyName: 'auditFindings',
  },

  // Approvals
  {
    name: 'pending_approvals',
    displayName: 'Pending Approvals',
    description: 'Items awaiting governance approval',
    category: 'approvals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'pendingApprovals',
  },
  {
    name: 'approval_cycle_time',
    displayName: 'Avg Approval Time',
    description: 'Average time to complete approvals',
    category: 'approvals',
    dataType: 'number',
    unit: 'days',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'approvalCycleTime',
  },
  {
    name: 'rejected_requests',
    displayName: 'Rejected Requests',
    description: 'Number of rejected approval requests this month',
    category: 'approvals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'rejectedRequests',
  },

  // Controls
  {
    name: 'active_controls',
    displayName: 'Active Controls',
    description: 'Number of active governance controls',
    category: 'controls',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'activeControls',
  },
  {
    name: 'control_effectiveness',
    displayName: 'Control Effectiveness',
    description: 'Percentage of controls operating effectively',
    category: 'controls',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 90, critical: 80 },
    palantirPropertyName: 'controlEffectiveness',
  },
  {
    name: 'controls_due_review',
    displayName: 'Controls Due Review',
    description: 'Controls requiring periodic review',
    category: 'controls',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'controlsDueReview',
  },
];

// ============================================================================
// VRO AGENT ATTRIBUTES
// ============================================================================
const VRO_ATTRIBUTES: AttributeDefinition[] = [
  // Value Metrics
  {
    name: 'total_expected_value',
    displayName: 'Expected Value',
    description: 'Total expected value from all initiatives',
    category: 'value',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalExpectedValue',
  },
  {
    name: 'realized_value',
    displayName: 'Realized Value',
    description: 'Value actually realized to date',
    category: 'value',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'realizedValue',
  },
  {
    name: 'value_gap',
    displayName: 'Value Gap',
    description: 'Difference between expected and realized value',
    category: 'value',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'calculated',
    calculationRule: 'total_expected_value - realized_value',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'valueGap',
  },
  {
    name: 'value_realization_rate',
    displayName: 'Realization Rate',
    description: 'Percentage of expected value realized',
    category: 'value',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: '(realized_value / total_expected_value) * 100',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 75, critical: 50 },
    palantirPropertyName: 'valueRealizationRate',
  },

  // ROI
  {
    name: 'portfolio_roi',
    displayName: 'Portfolio ROI',
    description: 'Return on investment across portfolio',
    category: 'roi',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: '((realized_value - total_investment) / total_investment) * 100',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'portfolioRoi',
  },
  {
    name: 'total_investment',
    displayName: 'Total Investment',
    description: 'Total investment across all initiatives',
    category: 'roi',
    dataType: 'currency',
    unit: 'USD',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalInvestment',
  },
  {
    name: 'payback_period',
    displayName: 'Avg Payback Period',
    description: 'Average time to recover investment',
    category: 'roi',
    dataType: 'number',
    unit: 'months',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'avgPaybackPeriod',
  },

  // Benefits
  {
    name: 'benefits_tracked',
    displayName: 'Benefits Tracked',
    description: 'Number of benefits being actively tracked',
    category: 'benefits',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'benefitsTracked',
  },
  {
    name: 'benefits_achieved',
    displayName: 'Benefits Achieved',
    description: 'Benefits that have been fully realized',
    category: 'benefits',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'benefitsAchieved',
  },
  {
    name: 'benefits_at_risk',
    displayName: 'Benefits at Risk',
    description: 'Benefits unlikely to be achieved as planned',
    category: 'benefits',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'benefitsAtRisk',
  },
  {
    name: 'value_by_category',
    displayName: 'Value by Category',
    description: 'Value distribution by benefit category',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-pie',
    palantirPropertyName: 'valueByCategory',
  },
];

// ============================================================================
// OCM AGENT ATTRIBUTES
// ============================================================================
const OCM_ATTRIBUTES: AttributeDefinition[] = [
  // Adoption
  {
    name: 'adoption_rate',
    displayName: 'Adoption Rate',
    description: 'Overall user adoption percentage',
    category: 'adoption',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 70, critical: 50 },
    palantirPropertyName: 'adoptionRate',
  },
  {
    name: 'active_users',
    displayName: 'Active Users',
    description: 'Number of actively engaged users',
    category: 'adoption',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'activeUsers',
  },
  {
    name: 'target_users',
    displayName: 'Target Users',
    description: 'Total target user population',
    category: 'adoption',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'targetUsers',
  },
  {
    name: 'adoption_trend',
    displayName: 'Adoption Trend',
    description: 'Historical adoption rate trend',
    category: 'adoption',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-line',
    palantirPropertyName: 'adoptionTrend',
  },

  // Readiness
  {
    name: 'change_readiness_score',
    displayName: 'Change Readiness',
    description: 'Organization change readiness score',
    category: 'readiness',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'change_readiness_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 70, critical: 50 },
    palantirPropertyName: 'changeReadinessScore',
  },
  {
    name: 'training_completion',
    displayName: 'Training Completion',
    description: 'Percentage of required training completed',
    category: 'readiness',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'progress',
    palantirPropertyName: 'trainingCompletion',
  },
  {
    name: 'users_trained',
    displayName: 'Users Trained',
    description: 'Number of users who completed training',
    category: 'readiness',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'usersTrained',
  },

  // Stakeholders
  {
    name: 'stakeholders_engaged',
    displayName: 'Stakeholders Engaged',
    description: 'Number of stakeholders actively engaged',
    category: 'stakeholders',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'stakeholdersEngaged',
  },
  {
    name: 'stakeholder_satisfaction',
    displayName: 'Stakeholder Satisfaction',
    description: 'Average stakeholder satisfaction score',
    category: 'stakeholders',
    dataType: 'percentage',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'stakeholderSatisfaction',
  },
  {
    name: 'resistance_level',
    displayName: 'Resistance Level',
    description: 'Measured change resistance level',
    category: 'stakeholders',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'resistance_level_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 30, critical: 50 },
    palantirPropertyName: 'resistanceLevel',
  },

  // Communications
  {
    name: 'communications_sent',
    displayName: 'Communications Sent',
    description: 'Total change communications sent',
    category: 'communications',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'communicationsSent',
  },
  {
    name: 'communication_effectiveness',
    displayName: 'Communication Effectiveness',
    description: 'Effectiveness score for change communications',
    category: 'communications',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'communicationEffectiveness',
  },
];

// ============================================================================
// PLANNING AGENT ATTRIBUTES
// ============================================================================
const PLANNING_ATTRIBUTES: AttributeDefinition[] = [
  // Capacity
  {
    name: 'total_capacity',
    displayName: 'Total Capacity',
    description: 'Total available team capacity',
    category: 'capacity',
    dataType: 'number',
    unit: 'story points',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalCapacity',
  },
  {
    name: 'allocated_capacity',
    displayName: 'Allocated Capacity',
    description: 'Capacity currently allocated to work',
    category: 'capacity',
    dataType: 'number',
    unit: 'story points',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'allocatedCapacity',
  },
  {
    name: 'capacity_utilization',
    displayName: 'Capacity Utilization',
    description: 'Percentage of capacity being utilized',
    category: 'capacity',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: '(allocated_capacity / total_capacity) * 100',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 90, critical: 100 },
    palantirPropertyName: 'capacityUtilization',
  },
  {
    name: 'available_capacity',
    displayName: 'Available Capacity',
    description: 'Remaining unallocated capacity',
    category: 'capacity',
    dataType: 'number',
    unit: 'story points',
    valueSource: 'calculated',
    calculationRule: 'total_capacity - allocated_capacity',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'availableCapacity',
  },

  // Backlog
  {
    name: 'backlog_size',
    displayName: 'Backlog Size',
    description: 'Total items in backlog',
    category: 'backlog',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'backlogSize',
  },
  {
    name: 'backlog_story_points',
    displayName: 'Backlog Points',
    description: 'Total story points in backlog',
    category: 'backlog',
    dataType: 'number',
    unit: 'points',
    valueSource: 'aggregated',
    aggregationMethod: 'sum',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'backlogStoryPoints',
  },
  {
    name: 'backlog_health',
    displayName: 'Backlog Health',
    description: 'Backlog refinement health score',
    category: 'backlog',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'backlog_health_rule',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'backlogHealth',
  },
  {
    name: 'sprints_planned',
    displayName: 'Sprints Planned',
    description: 'Number of fully planned upcoming sprints',
    category: 'backlog',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'sprintsPlanned',
  },

  // Sprint
  {
    name: 'current_sprint_progress',
    displayName: 'Sprint Progress',
    description: 'Current sprint completion percentage',
    category: 'sprint',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'progress',
    palantirPropertyName: 'currentSprintProgress',
  },
  {
    name: 'sprint_velocity',
    displayName: 'Sprint Velocity',
    description: 'Average velocity over recent sprints',
    category: 'sprint',
    dataType: 'number',
    unit: 'points',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'trend-card',
    palantirPropertyName: 'sprintVelocity',
  },
  {
    name: 'sprint_burndown',
    displayName: 'Sprint Burndown',
    description: 'Current sprint burndown data',
    category: 'sprint',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-line',
    palantirPropertyName: 'sprintBurndown',
  },

  // Roadmap
  {
    name: 'features_in_roadmap',
    displayName: 'Roadmap Features',
    description: 'Features planned in roadmap',
    category: 'roadmap',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'featuresInRoadmap',
  },
  {
    name: 'roadmap_coverage',
    displayName: 'Roadmap Coverage',
    description: 'Percentage of initiatives with roadmap items',
    category: 'roadmap',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'roadmapCoverage',
  },
];

// ============================================================================
// OKR AGENT ATTRIBUTES
// ============================================================================
const OKR_ATTRIBUTES: AttributeDefinition[] = [
  // Objectives
  {
    name: 'total_objectives',
    displayName: 'Total Objectives',
    description: 'Total number of objectives',
    category: 'objectives',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalObjectives',
  },
  {
    name: 'objectives_on_track',
    displayName: 'Objectives On Track',
    description: 'Objectives progressing as planned',
    category: 'objectives',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'objectivesOnTrack',
  },
  {
    name: 'objectives_at_risk',
    displayName: 'Objectives at Risk',
    description: 'Objectives at risk of not being achieved',
    category: 'objectives',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 4 },
    palantirPropertyName: 'objectivesAtRisk',
  },
  {
    name: 'okr_achievement_rate',
    displayName: 'OKR Achievement Rate',
    description: 'Percentage of OKRs achieved',
    category: 'objectives',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 70, critical: 50 },
    palantirPropertyName: 'okrAchievementRate',
  },

  // Key Results
  {
    name: 'total_key_results',
    displayName: 'Total Key Results',
    description: 'Total number of key results',
    category: 'key_results',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalKeyResults',
  },
  {
    name: 'key_results_completed',
    displayName: 'Key Results Completed',
    description: 'Key results that have been completed',
    category: 'key_results',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'keyResultsCompleted',
  },
  {
    name: 'avg_key_result_progress',
    displayName: 'Avg KR Progress',
    description: 'Average progress across all key results',
    category: 'key_results',
    dataType: 'percentage',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'avgKeyResultProgress',
  },

  // Alignment
  {
    name: 'alignment_score',
    displayName: 'Alignment Score',
    description: 'OKR alignment with strategic goals',
    category: 'alignment',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'okr_alignment_rule',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'alignmentScore',
  },
  {
    name: 'cascaded_objectives',
    displayName: 'Cascaded Objectives',
    description: 'Objectives properly cascaded through org',
    category: 'alignment',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'cascadedObjectives',
  },
  {
    name: 'okr_coverage',
    displayName: 'OKR Coverage',
    description: 'Percentage of teams with defined OKRs',
    category: 'alignment',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'okrCoverage',
  },

  // Progress
  {
    name: 'okr_progress_trend',
    displayName: 'OKR Progress Trend',
    description: 'Historical OKR progress trend',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-line',
    palantirPropertyName: 'okrProgressTrend',
  },
  {
    name: 'okrs_by_status',
    displayName: 'OKRs by Status',
    description: 'Distribution of OKRs by status',
    category: 'analysis',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-pie',
    palantirPropertyName: 'okrsByStatus',
  },
];

// ============================================================================
// INTEGRATED AGENT ATTRIBUTES
// ============================================================================
const INTEGRATED_ATTRIBUTES: AttributeDefinition[] = [
  // Portfolio Overview
  {
    name: 'portfolio_score',
    displayName: 'Portfolio Score',
    description: 'Overall portfolio health score combining all dimensions',
    category: 'overview',
    dataType: 'percentage',
    valueSource: 'rulebricks',
    calculationRule: 'portfolio_composite_score_rule',
    defaultWidgetType: 'gauge',
    thresholds: { warning: 70, critical: 50 },
    palantirPropertyName: 'portfolioScore',
  },
  {
    name: 'executive_summary_status',
    displayName: 'Executive Status',
    description: 'High-level portfolio status indicator',
    category: 'overview',
    dataType: 'status',
    valueSource: 'rulebricks',
    calculationRule: 'executive_status_rule',
    defaultWidgetType: 'status-badge',
    palantirPropertyName: 'executiveStatus',
  },
  {
    name: 'total_initiatives',
    displayName: 'Total Initiatives',
    description: 'Total number of active initiatives',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'totalInitiatives',
  },
  {
    name: 'initiatives_on_track',
    displayName: 'Initiatives On Track',
    description: 'Initiatives meeting all targets',
    category: 'overview',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'initiativesOnTrack',
  },

  // Cross-Domain Metrics
  {
    name: 'cross_domain_score',
    displayName: 'Cross-Domain Score',
    description: 'Composite score from all domain agents',
    category: 'cross_domain',
    dataType: 'percentage',
    valueSource: 'calculated',
    calculationRule: 'avg(finops_score, tmo_score, risk_score, ocm_score)',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'crossDomainScore',
  },
  {
    name: 'agent_agreement_level',
    displayName: 'Agent Agreement',
    description: 'Level of agreement between agent assessments',
    category: 'cross_domain',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'agentAgreementLevel',
  },
  {
    name: 'conflicting_recommendations',
    displayName: 'Conflicts',
    description: 'Number of conflicting agent recommendations',
    category: 'cross_domain',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'conflictingRecommendations',
  },

  // Insights
  {
    name: 'active_insights',
    displayName: 'Active Insights',
    description: 'Total active insights from all agents',
    category: 'insights',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'activeInsights',
  },
  {
    name: 'high_priority_insights',
    displayName: 'High Priority Insights',
    description: 'Insights requiring immediate attention',
    category: 'insights',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 5, critical: 10 },
    palantirPropertyName: 'highPriorityInsights',
  },
  {
    name: 'insights_by_agent',
    displayName: 'Insights by Agent',
    description: 'Distribution of insights by source agent',
    category: 'insights',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-bar',
    palantirPropertyName: 'insightsByAgent',
  },

  // Actions
  {
    name: 'pending_actions',
    displayName: 'Pending Actions',
    description: 'Actions awaiting execution',
    category: 'actions',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'pendingActions',
  },
  {
    name: 'actions_completed_today',
    displayName: 'Actions Today',
    description: 'Actions completed today',
    category: 'actions',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'actionsCompletedToday',
  },
];

// ============================================================================
// NOTIFICATION AGENT ATTRIBUTES
// ============================================================================
const NOTIFICATION_ATTRIBUTES: AttributeDefinition[] = [
  // Alerts
  {
    name: 'active_alerts',
    displayName: 'Active Alerts',
    description: 'Total number of active alerts',
    category: 'alerts',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'activeAlerts',
  },
  {
    name: 'critical_alerts',
    displayName: 'Critical Alerts',
    description: 'Alerts requiring immediate attention',
    category: 'alerts',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'criticalAlerts',
  },
  {
    name: 'alerts_resolved_today',
    displayName: 'Resolved Today',
    description: 'Alerts resolved today',
    category: 'alerts',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'alertsResolvedToday',
  },
  {
    name: 'avg_resolution_time',
    displayName: 'Avg Resolution Time',
    description: 'Average time to resolve alerts',
    category: 'alerts',
    dataType: 'number',
    unit: 'hours',
    valueSource: 'aggregated',
    aggregationMethod: 'average',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'avgResolutionTime',
  },

  // Approvals
  {
    name: 'pending_approvals',
    displayName: 'Pending Approvals',
    description: 'Approvals awaiting HITL decision',
    category: 'approvals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'pendingApprovals',
  },
  {
    name: 'approvals_due_today',
    displayName: 'Due Today',
    description: 'Approvals due today',
    category: 'approvals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'approvalsDueToday',
  },
  {
    name: 'overdue_approvals',
    displayName: 'Overdue Approvals',
    description: 'Approvals past their due date',
    category: 'approvals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 2, critical: 5 },
    palantirPropertyName: 'overdueApprovals',
  },
  {
    name: 'approval_rate',
    displayName: 'Approval Rate',
    description: 'Percentage of requests approved',
    category: 'approvals',
    dataType: 'percentage',
    valueSource: 'calculated',
    defaultWidgetType: 'gauge',
    palantirPropertyName: 'approvalRate',
  },

  // Signals
  {
    name: 'signals_broadcast_today',
    displayName: 'Signals Today',
    description: 'Agent signals broadcast today',
    category: 'signals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    palantirPropertyName: 'signalsBroadcastToday',
  },
  {
    name: 'signals_by_type',
    displayName: 'Signals by Type',
    description: 'Distribution of signals by type',
    category: 'signals',
    dataType: 'array',
    valueSource: 'aggregated',
    defaultWidgetType: 'chart-pie',
    palantirPropertyName: 'signalsByType',
  },
  {
    name: 'escalation_count',
    displayName: 'Escalations',
    description: 'Number of escalated notifications',
    category: 'signals',
    dataType: 'number',
    valueSource: 'aggregated',
    aggregationMethod: 'count',
    defaultWidgetType: 'stat-card',
    thresholds: { warning: 3, critical: 5 },
    palantirPropertyName: 'escalationCount',
  },
];

// ============================================================================
// AGENT TO ATTRIBUTES MAP
// ============================================================================
const AGENT_ATTRIBUTES_MAP: Record<string, AttributeDefinition[]> = {
  finops: FINOPS_ATTRIBUTES,
  tmo: TMO_ATTRIBUTES,
  risk: RISK_ATTRIBUTES,
  pmo: PMO_ATTRIBUTES,
  governance: GOVERNANCE_ATTRIBUTES,
  vro: VRO_ATTRIBUTES,
  ocm: OCM_ATTRIBUTES,
  planning: PLANNING_ATTRIBUTES,
  okr: OKR_ATTRIBUTES,
  integrated: INTEGRATED_ATTRIBUTES,
  notification: NOTIFICATION_ATTRIBUTES,
};

// ============================================================================
// SEED FUNCTION
// ============================================================================
export async function seedAgentAttributes() {
  console.log('[Seed] Starting agent attributes seed...');

  let created = 0;
  let updated = 0;

  for (const [agentId, attributes] of Object.entries(AGENT_ATTRIBUTES_MAP)) {
    console.log(`[Seed] Processing ${attributes.length} attributes for agent: ${agentId}`);

    for (const attr of attributes) {
      const attributeId = `${agentId}_${attr.name}`;

      // Check if exists
      const existing = await db.execute(sql`
        SELECT id FROM agent_attributes WHERE id = ${attributeId} LIMIT 1
      `);

      if (existing.rows.length > 0) {
        // Update existing
        await db.execute(sql`
          UPDATE agent_attributes SET
            display_name = ${attr.displayName},
            description = ${attr.description || null},
            category = ${attr.category},
            data_type = ${attr.dataType},
            unit = ${attr.unit || null},
            format = ${attr.format || null},
            value_source = ${attr.valueSource},
            calculation_rule = ${attr.calculationRule || null},
            aggregation_method = ${attr.aggregationMethod || null},
            default_widget_type = ${attr.defaultWidgetType},
            thresholds = ${attr.thresholds ? JSON.stringify(attr.thresholds) : null},
            palantir_property_name = ${attr.palantirPropertyName || null},
            refresh_interval = ${attr.refreshInterval || 300},
            updated_at = CURRENT_TIMESTAMP
          WHERE id = ${attributeId}
        `);
        updated++;
      } else {
        // Insert new
        await db.execute(sql`
          INSERT INTO agent_attributes (
            id, agent_id, name, display_name, description, category,
            data_type, unit, format, value_source, calculation_rule,
            aggregation_method, default_widget_type, thresholds,
            palantir_property_name, refresh_interval
          ) VALUES (
            ${attributeId},
            ${agentId},
            ${attr.name},
            ${attr.displayName},
            ${attr.description || null},
            ${attr.category},
            ${attr.dataType},
            ${attr.unit || null},
            ${attr.format || null},
            ${attr.valueSource},
            ${attr.calculationRule || null},
            ${attr.aggregationMethod || null},
            ${attr.defaultWidgetType},
            ${attr.thresholds ? JSON.stringify(attr.thresholds) : null},
            ${attr.palantirPropertyName || null},
            ${attr.refreshInterval || 300}
          )
        `);
        created++;
      }
    }
  }

  // Count totals
  const totalCount = await db.execute(sql`SELECT COUNT(*) as count FROM agent_attributes`);
  const total = totalCount.rows[0]?.count || 0;

  console.log(`[Seed] Agent attributes: ${created} created, ${updated} updated, ${total} total`);
  console.log('[Seed] Agent attributes seed complete!');

  return { created, updated, total };
}

// Run if called directly
if (process.argv[1]?.includes('seed-agent-attributes')) {
  seedAgentAttributes()
    .then((result) => {
      console.log('[Seed] Result:', result);
      process.exit(0);
    })
    .catch((err) => {
      console.error('[Seed] Error:', err);
      process.exit(1);
    });
}
